### ISSUE TITLE
Cannot search for URIs/URLs with their protocols: We must escape URI/URL protocols for solr

### ISSUE THREAD

**Issue by pnbecker** [DSpace/DSpace#10151]
## Describe the bug
When searching for a url starting with the protocol like `http://` or `https://` in DSpace 8, an error is returned.

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/42f8d6a4-7947-4c3d-a7ee-a329394deec1" />

The backend logs:

```
org.dspace.app.rest.repository.DiscoveryRestRepository @ Error while searching with Discovery
org.dspace.discovery.SearchServiceException: Error from server at http://<solr-server-url>:8983/solr/search: org.apache.solr.search.SyntaxError: Cannot parse 'https://demo.dspace.org/handle/10673/1480 ': Lexical error at line 1, column 8.  Encountered: "/" (47), after : "/"
        at org.dspace.discovery.SolrServiceImpl.search(SolrServiceImpl.java:774) ~[dspace-api-8.0.jar:8.0]
        at org.dspace.discovery.SolrServiceImpl.search(SolrServiceImpl.java:753) ~[dspace-api-8.0.jar:8.0]
        at org.dspace.app.rest.repository.DiscoveryRestRepository.getSearchObjects(DiscoveryRestRepository.java:107) ~[dspace-server-webapp-8.0.jar:8.0]
        ...
```

## To Reproduce
1. Go to https://demo.dspace.org
2. Open any item
3. Copy the URI from dc.identifier.uri including the prefixing protocoll
4. paste the URI to the search and submit the search request

## Expected behavior
It should be possible to search for URIs including its protocol. People are searching for DOIs, handles and even dspace Item View URLs. We should even think about adding the URL of the item view to solr if it is not included yet.

## Related
The escaping of our SOLR queries is complicated as we want to support to use SOLR queries language or search for certain fields directly in SOLR.

* #7531
* #2377 
* #6858 
* #6162

**Comment by alanorth** [comment]
I'm in the habit of manually escaping the colons. :\
