### ISSUE TITLE
"discovery" event consumer throws ClassCastException on `IndexableWorkflowItem` and `IndexableWorkspaceItem`

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2989]
**Describe the bug**
After a WorkflowItem is created, the "discovery" event consumer is notified.  That "discovery" event consumer throws this error:
```
2020-10-05 16:37:25,255 ERROR org.dspace.event.BasicDispatcher @ Consumer("discovery").consume threw: java.lang.ClassCastException: class org.dspace.discovery.indexobject.IndexableWorkflowItem cannot be cast to class org.dspace.discovery.indexobject.IndexableDSpaceObject (org.dspace.discovery.indexobject.IndexableWorkflowItem and org.dspace.discovery.indexobject.IndexableDSpaceObject are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @44984379)
java.lang.ClassCastException: class org.dspace.discovery.indexobject.IndexableWorkflowItem cannot be cast to class org.dspace.discovery.indexobject.IndexableDSpaceObject (org.dspace.discovery.indexobject.IndexableWorkflowItem and org.dspace.discovery.indexobject.IndexableDSpaceObject are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @44984379)
        at org.dspace.discovery.indexobject.AbstractIndexableObject.equals(AbstractIndexableObject.java:33) ~[dspace-api-7.0-beta4-SNAPSHOT.jar:7.0-beta4-SNAPSHOT]
        at java.util.HashMap.putVal(HashMap.java:630) ~[?:?]
        at java.util.HashMap.put(HashMap.java:607) ~[?:?]
        at java.util.HashSet.add(HashSet.java:220) ~[?:?]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:352) ~[?:?]
        at org.dspace.discovery.IndexEventConsumer.consume(IndexEventConsumer.java:133) ~[dspace-api-7.0-beta4-SNAPSHOT.jar:7.0-beta4-SNAPSHOT]
        at org.dspace.event.BasicDispatcher.dispatch(BasicDispatcher.java:104) [dspace-api-7.0-beta4-SNAPSHOT.jar:7.0-beta4-SNAPSHOT]
        at org.dspace.core.Context.dispatchEvents(Context.java:455) [dspace-api-7.0-beta4-SNAPSHOT.jar:7.0-beta4-SNAPSHOT]
        at org.dspace.core.Context.commit(Context.java:424) [dspace-api-7.0-beta4-SNAPSHOT.jar:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.createAndReturn(DSpaceRestRepository.java:307) [classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) [classes/:7.0-beta4-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.WorkflowItemRestRepository$$EnhancerBySpringCGLIB$$51004136.createAndReturn(<generated>) [classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.postUriListInternal(RestResourceController.java:460) [classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.postWithUriListContentType(RestResourceController.java:405) [classes/:7.0-beta4-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

UPDATE: The same error appears also for `IndexableWorkspaceItem`.

**To Reproduce**
1. Create a Collection with workflow enabled.
2. Deposit a new Item into that collection, triggering the creation of a WorkflowItem.
3. Look at your `dspace.log`, which should show the above ClassCastException

**Expected behavior**
No error should be thrown & the WorkflowItem or WorkflowItem will be indexed as necessary for display/search in MyDSpace, etc.

**Comment by KevinVdV** [comment]
I estimate this to be half a day of work (this includes tests).
