### ISSUE TITLE
NullPointerException occurs when accessing WorkflowItem after deleting the Submitter

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2994]
**Describe the bug**
Discovered in testing of https://github.com/DSpace/DSpace/pull/2928#pullrequestreview-502244452

If I delete a submitter while they have an item in Workflow, the deletion correctly succeeds & the Item is correctly kept in Workflow. However, from the UI, the Item in Workflow is no longer accessible (it throws a NullPointerException as the submitter is now null).  The MyDSpace UI "hangs" indefinitely when this error occurs.

This error appears in the dspace.log when this problem occurs:
```
2020-10-05 16:38:57,968 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.NullPointerException: null
        at org.dspace.app.rest.converter.ConverterService.toRest(ConverterService.java:110) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.AInprogressItemConverter.fillFromModel(AInprogressItemConverter.java:70) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.WorkflowItemConverter.convert(WorkflowItemConverter.java:36) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.WorkflowItemConverter.convert(WorkflowItemConverter.java:24) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.ConverterService.toRest(ConverterService.java:111) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.PoolTaskConverter.convert(PoolTaskConverter.java:38) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.PoolTaskConverter.convert(PoolTaskConverter.java:24) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.DiscoverResultConverter.convertDSpaceObject(DiscoverResultConverter.java:98) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.DiscoverResultConverter.addSearchResults(DiscoverResultConverter.java:78) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.converter.DiscoverResultConverter.convert(DiscoverResultConverter.java:57) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.repository.DiscoveryRestRepository.getSearchObjects(DiscoveryRestRepository.java:115) ~[classes/:7.0-beta4-SNAPSHOT]
        at org.dspace.app.rest.DiscoveryRestController.getSearchObjects(DiscoveryRestController.java:153) ~[classes/:7.0-beta4-SNAPSHOT]
```

Based on the stacktrace, the error appears to be here: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java#L70  That `fillFromModel()` method should likely be verifying that the submitter is _not_ null before using it.

**To Reproduce**
1. Create a new EPerson (as needed) who is an Administrator
2. Find a Collection that has workflow approval enabled. Submit to it.
3. Complete the submission...it goes into workflow approval
4. Delete the EPerson who submitted the item (it will succeed)
5. Now, login as a different user who can approve/reject the submission that was created. The Workflow item list in that person's MyDSpace will "hang" indefinitely...in the dspace.log you'll see the above NullPointerException.

**Expected behavior**
Obviously, the expected behavior is that no error should appear in this scenario & the Item in Workflow should still be reviewable even though the submitter is set to null.

Additionally, this change should come with a **test** to prove that it works.  The current test related to this action (`DeleteEpersonSubmitterIT.testWorkflowItemSubmitterDelete()`) was set to `@Ignored` as can be seen here https://github.com/DSpace/DSpace/pull/2928#discussion_r500444894   Therefore, this test should no longer be Ignored, and should prove that a NPE will not occur in this scenario.

**Related work**
Related to the code in https://github.com/DSpace/DSpace/pull/2928

**Comment by benbosman** [comment]
I've verified the issues mentioned above, and it seems changing https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java#L70 doesn't fix `DeleteEpersonSubmitterIT.testWorkflowItemSubmitterDelete()`

So for this ticket we'll need to:
* Create a test for the issue in https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java#L70, it should fail
* Fix this issue, and verify the test now succeeds
* Re-enable `DeleteEpersonSubmitterIT.testWorkflowItemSubmitterDelete()`, it should fail
* Identify the issue with `DeleteEpersonSubmitterIT.testWorkflowItemSubmitterDelete()`, and fix it. Verify the test now succeeds

**Comment by tdonohue** [comment]
Thanks for the summary, @benbosman .  The approach suggested & estimate sounds good to me.

**Comment by benbosman** [comment]
This is something we can work on since we've worked on https://github.com/DSpace/DSpace/pull/2928 as well

**Comment by tdonohue** [comment]
Sounds good @benbosman . I've assigned to you & moved to "in progress"
