### ISSUE TITLE
Packager  AIP Backup / Restore CLI options createMetadataFields does not exist

### ISSUE THREAD

**Issue by ubks-mp** [DSpace/DSpace#3215]
**Describe the bug**
The documentation for DSpace 6 and DSpace 7 states the existence of the option **createMetadataField**=true|false in
[https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore](url) (Additional Packager Options).
This option is not existing anymore after DSpace 5 and is commented out in the code [https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/packager/DSpaceAIPIngester.java](url) line 247 ff.
Usual stack trace is 
```
org.dspace.content.crosswalk.CrosswalkException: The 'jaja.uri' element has not been defined in this DSpace instance. 
        at org.dspace.content.crosswalk.CrosswalkMetadataValidator.checkMetadata(CrosswalkMetadataValidator.java:110)
        at org.dspace.content.crosswalk.XSLTIngestionCrosswalk.applyDimField(XSLTIngestionCrosswalk.java:102)
        at org.dspace.content.crosswalk.XSLTIngestionCrosswalk.applyDim(XSLTIngestionCrosswalk.java:79)
        at org.dspace.content.crosswalk.XSLTIngestionCrosswalk.applyDim(XSLTIngestionCrosswalk.java:82)
        at org.dspace.content.crosswalk.XSLTIngestionCrosswalk.ingestDIM(XSLTIngestionCrosswalk.java:224)
        at org.dspace.content.crosswalk.AIPDIMCrosswalk.ingest(AIPDIMCrosswalk.java:185)
        at org.dspace.content.packager.METSManifest.crosswalkXmd(METSManifest.java:1135)
        at org.dspace.content.packager.METSManifest.crosswalkItemDmd(METSManifest.java:1025)
        at org.dspace.content.packager.DSpaceAIPIngester.crosswalkObjectDmd(DSpaceAIPIngester.java:155)
        at org.dspace.content.packager.AbstractMETSIngester.replaceObject(AbstractMETSIngester.java:653)
        at org.dspace.content.packager.AbstractMETSIngester.replace(AbstractMETSIngester.java:1092)
        at org.dspace.content.packager.AbstractPackageIngester.replaceAll(AbstractPackageIngester.java:275)
        at org.dspace.app.packager.Packager.replace(Packager.java:684)
        at org.dspace.app.packager.Packager.main(Packager.java:361)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:272)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:128)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:93)
org.dspace.content.crosswalk.CrosswalkException: The 'jaja.uri' element has not been defined in this DSpace instance. 
```

Options are generally not checked for validity, e.g. you can define an option whith -o and get no error.

**To Reproduce**
Ingest a package (AIP) with metadata fields not included in the metadata registry with 
`~/bin/dspace packager -r  -u -a -e <mail> -p 123456789/0 -t AIP -f -o createMetadataFields=true  sitewide.zip`
Choose any option you like
`~/bin/dspace packager -r  -u -a -e <mail> -p 123456789/0 -t AIP -f -o thereisaholeinthebucket=henry  sitewide.zip`

**Expected behavior**
Validate options.
Update docs.

**Comment by tdonohue** [comment]
Removed this option from Docs in 7.x/8.x/9.x/10.x.  See for example https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore
