### ISSUE TITLE
Concurrent deletion of large communities/collections can cause trouble

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3243]
**Describe the bug**
During the testhaton the solr search index was out of sync with the database. This result in empty search results when indeed there were still some contents.
The main reason for that is because the first page of results contains references only to objects that were deleted.

**To Reproduce**
Looking to the apache/dspace log files we where able to spot the possible cause
Apache log

Compound Journal Community
```
****** - "" [21/Apr/2021:13:43:37 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 204 1614 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:38 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:40 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:43 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:42 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```

Publications community
```
****** - "" [21/Apr/2021:13:45:15 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 204 1054 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:45:40 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:45:45 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```

but similar logs exists also for the other test communities.

Looking to the dspace.log file for the entries related to the publications deletion we found
```
...
2021-04-21 13:45:51,844 WARN  org.dspace.discovery.IndexEventConsumer @ MODIFY_METADATA event, could not get object for ITEM id=e7bd0d24-e83a-486a-bc0c-8aaaeb19dc7d, perhaps it has been deleted.
2021-04-21 13:45:51,845 WARN  org.dspace.discovery.IndexEventConsumer @ MODIFY event, could not get object for ITEM id=e7bd0d24-e83a-486a-bc0c-8aaaeb19dc7d, perhaps it has been deleted.
2021-04-21 13:45:51,845 ERROR org.dspace.event.BasicDispatcher @ Consumer("discovery").consume threw: java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.dspace.discovery.indexobject.factory.IndexObjectFactoryFactory.getIndexableObjects(IndexObjectFactoryFactory.java:90) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.discovery.IndexEventConsumer.consume(IndexEventConsumer.java:159) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.event.BasicDispatcher.dispatch(BasicDispatcher.java:104) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.core.Context.dispatchEvents(Context.java:455) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.core.Context.commit(Context.java:424) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.deleteById(DSpaceRestRepository.java:173) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) [classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.CommunityRestRepository$$EnhancerBySpringCGLIB$$4616f34f.deleteById(<generated>) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.deleteInternal(RestResourceController.java:1065) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.delete(RestResourceController.java:1049) [classes/:7.0-beta5-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor807.invoke(Unknown Source) ~[?:?]

....

2021-04-21 13:45:56,869 INFO  org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2021-04-21 13:45:56,869 ERROR org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid], SQL: update public.collection set admin=?, logo_bitstream_id=?, submitter=?, template_item_id=? where uuid=?
2021-04-21 13:45:56,870 INFO  org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2021-04-21 13:45:56,870 ERROR org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid], SQL: update public.collection set admin=?, logo_bitstream_id=?, submitter=?, template_item_id=? where uuid=?
2021-04-21 13:45:56,869 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1535) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:203) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.dao.impl.HandleDAOImpl.getHandlesByDSpaceObject(HandleDAOImpl.java:62) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.HandleServiceImpl.getInternalHandles(HandleServiceImpl.java:347) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.HandleServiceImpl.findHandle(HandleServiceImpl.java:264) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.identifier.VersionedHandleIdentifierProvider.lookup(VersionedHandleIdentifierProvider.java:301) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.identifier.IdentifierServiceImpl.lookup(IdentifierServiceImpl.java:151) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.DSpaceObjectServiceImpl.getIdentifiers(DSpaceObjectServiceImpl.java:89) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.rawDelete(ItemServiceImpl.java:683) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:671) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:71) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.removeTemplateItem(CollectionServiceImpl.java:594) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.delete(CollectionServiceImpl.java:721) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.delete(CollectionServiceImpl.java:75) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.removeCollection(CommunityServiceImpl.java:428) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.rawDelete(CommunityServiceImpl.java:534) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.delete(CommunityServiceImpl.java:498) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.delete(CommunityServiceImpl.java:51) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.CommunityRestRepository.delete(CommunityRestRepository.java:273) ~[classes/:7.0-beta5-SNAPSHOT]
```

in the between we see a lot of modify event related to deleted objects and the first attempt to retrieve deleted object still present in the search indexes

**Expected behavior**
Concurrent deletion should be managed or at least the search index should not end out of sync

**Related work**
A possible solution/workaround could be to introduce a mechanism to self-maintain the solr index in a good status. When during a search stale objects are detected they should be removed and the search automatically re-run

**Comment by tdonohue** [comment]
@abollini : Having now read this completely, your idea to "auto-detect stale objects and remove them" is interesting.  As you noted in the meeting, it wouldn't be the best performance (and we may want to *log* when stale objects were found in Solr & therefore removed, including the type/uuid of each stale obj found).  But, it should fix the issue, assuming it doesn't occur frequently.

We'd also though need to keep in mind that stale objects may not always appear next to each other & may appear suddenly on any page of results.  You could have a completely valid first few pages of results, only to find 5 stale objects in a row on page 3.  Or, several stale objects could appear in between real objects on page 10.  So, we'd have to be careful to keep other scenarios in mind.

In general though, this behavior does sound very similar to what we saw in ticket #3140 / PR #3181. But, that one was more about deleted Items causing issues in Solr, and this new ticket is now about deleted Communities/Collections.

**Comment by tdonohue** [comment]
Moving this into 7.0 with "high priority"...but, I've also flagged as `needs discussion` as it sounds like an exact solution is not yet obvious.

**Comment by abollini** [comment]
the stale objects created by this incident were not only communities or collections but also a lot of items. Indeed there where more the 430 stale objects in the index before the re-index. Due to an small issue in the restoring instruction (it was used the index-discovery with the -b flag instead than -f) now fixed on the Entities Release Data I cannot be 100% sure to have reindexed the demo website correctly after resetting its content last Friday so there is also a chances that all the stale items that I have seen today were related to this other issue.

All that said, I'm still convinced that have a way to treat an of sync solr index without blocking the dspace features is useful.

To summarize the idea:
1. stale objects should still be logged (at ERROR level and #3244 should help to make the log more useful in understanding the root cause)
2. the rest side should fix only the requested result page, i.e. if I'm asking for the 1st page and I got back 10 real results nothing is required. When I ask for the second page and I got 10 results but 2 are missing from the db I should delete the two missing entries from solr and perform again the request for the second page until I get a complete list of result (i.e. the number of results that solr return 10 or less must match with the objects retrieved from the database)
3. in the worst scenario asking for the first page could result in cleaning page by page all the stale objects but most of time stale objects will stay until someone not reach them
4. keep in mind that we have hit this issue already several times so there is always a chance that some feature / edge scenario can produce it now or in the future. If we want to have a stable release we should avoid that a single issue can turn a production site in a completely unusable state maybe just because there are 10 stale objects just in the first page of results
5. stale objects can easily be created by improper scripts (maybe they disable the consumers) or working at the database level...  with such solution in place it would be possible for a large repository to operate with such inconsistency and have it fixed automatically over the time instead that going for a full reindex

My estimation to build such procedure an a basic test is between 4-8 hours

**Comment by tdonohue** [comment]
@abollini : I'm fine with moving this forward based on your summary & estimate.  However, I would caution you to make sure to let us know if your solution turns out to need more complexity. It sounds like it should work, but if you start going over 8 hours, then we may need to take a step back and see if there's a flaw in the approach that we overlooked.

In any case, I'll take off the `needs discussion` flag, and add the estimate & assign back to you for you & your team to start work.

(As a sidenote, I still want to make sure we keep an eye out for possible bugs like #3140 that could be causing *more stale items*.  Those can be treated as a separate ticket though as they are discovered.)
