### ISSUE TITLE
PDFBox runs on more than PDF Bitstreams

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3263]
**Describe the bug**
Copied from https://jira.lyrasis.org/browse/DS-3873 , originally reported by @KingKrimmson. I've rediscovered this issue during Testathon.

PDFBoxThumbnail media filter is currently configured to run on more than just PDFs. This consistently results in an error in the logs:

```
ERROR filtering, skipping bitstream #7f142dd0-fca6-4533-b966-19b1354e9a9d java.io.IOException: Error: Header doesn't contain versioninfo
java.io.IOException: Error: Header doesn't contain versioninfo
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:244)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:966)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:868)
        at org.dspace.app.mediafilter.PDFBoxThumbnail.getDestinationStream(PDFBoxThumbnail.java:80)
        at org.dspace.app.mediafilter.MediaFilterServiceImpl.processBitstream(MediaFilterServiceImpl.java:358)
        at org.dspace.app.mediafilter.MediaFilterServiceImpl.filterBitstream(MediaFilterServiceImpl.java:286)
        at org.dspace.app.mediafilter.MediaFilterServiceImpl.filterItem(MediaFilterServiceImpl.java:180)
        at org.dspace.app.mediafilter.MediaFilterServiceImpl.applyFiltersItem(MediaFilterServiceImpl.java:158)
        at org.dspace.app.mediafilter.MediaFilterCLITool.main(MediaFilterCLITool.java:315)
```
This can be fixed by modifying .getInputMIMETypes() to only return "Adobe PDF" instead of all ImageIO Reader Mimetypes.

**To Reproduce**
1. Upload an image to an Item (either preexisting or new), while paying attention to the Item's handle
2. From commandline run `./dspace filter-media -f -i [item-handle-prefix]/[item-handle-suffix]
3. You'll see the image is filtered, but you'll also see the above error from PDFBox (as PDFBox also attempts to filter the image).

**Related work**
An old PR exists at #2123 but it needs to be updated so that it can be merged.

**Comment by tdonohue** [comment]
@benbosman : Assigning this to your team for review/work.  Please note that @KingKrimmson created a PR a few years back that *should* fix this, but it just needs updating.  #2123

**Comment by benbosman** [comment]
I'd expect this to require 2 hours to upgrade the code, and test the functionality still works while no longer spawning the errors
This is under the assumption no tests have to be implemented (only manual tests)

**Comment by tdonohue** [comment]
@benbosman : That sounds fine to me.  As MediaFilters currently don't have ITs, and this is a very tiny bug fix, it can just be manually tested.  I'll add the estimate & assign back to you for your team to update/recreate the PR.

**Comment by tdonohue** [comment]
Backported to 6.x in #2124
