### ISSUE TITLE
[DS-3975] Checksum checker fails to complete with large repositories

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7322]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3975">[DS-3975]</a> created by cwilper</i>
<p>In repositories with many bitstreams, the checksum checker can fail to complete (hang or die) due to memory constraints. This problem appears to have been introduced with the move to Hibernate.</p>
<h2><a name="Analysis"></a>Analysis</h2>

<p>We examined the issue in detail on a recent DSpace 6.x deployment and determined that it gets stuck in the following code: </p>

<p>{{{{at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1230)<br/>
at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)<br/>
at org.dspace.content.dao.impl.BitstreamDAOImpl.findBitstreamsWithNoRecentChecksum(BitstreamDAOImpl.java:91)<br/>
at org.dspace.content.BitstreamServiceImpl.findBitstreamsWithNoRecentChecksum(BitstreamServiceImpl.java:365)<br/>
at org.dspace.checker.MostRecentChecksumServiceImpl.updateMissingBitstreams(MostRecentChecksumServiceImpl.java:121)<br/>
at org.dspace.checker.CheckerCommand.process(CheckerCommand.java:115)<br/>
at org.dspace.app.checker.ChecksumChecker.main(ChecksumChecker.java:232)}}}}</p>

<p>Notice that findBitstreamsWIthNoRecentChecksum returns a list, rather than an iterator of objects (or ids). This means it is relying on Hibernate to read, into memory, all Bitstream objects representing those that don't have a recent checksum.</p>

<p>This is an impractical approach with large repositories, and results in the heap filling up and the process either hanging or dying.</p>

<p>The approach that was used in DSpace 5.x (pre-Hibernate), was to call: </p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/checker/BitstreamInfoDAO.java#L302" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/checker/BitstreamInfoDAO.java#L302</a><br/>
...which calls:<br/>
<a href="https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/checker/ChecksumHistoryDAO.java#L181" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/checker/ChecksumHistoryDAO.java#L181</a><br/>
...which just executes a single SQL statement to insert necessary rows into the checksum_history table.</p>

<p>In the move to Hibernate, this was turned into the following:</p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/checker/MostRecentChecksumServiceImpl.java#L105" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/checker/MostRecentChecksumServiceImpl.java#L105</a></p>

**Comment by minurmin** [comment]
@tdonohue I'd like to bring to attention that this issue still still exists in newer DSpace versions and is almost a blocker if one tries to run checker on a database where large amount of bitstreams needs to be added for checking. Please see #10413 for updated fix.

**Comment by tdonohue** [comment]
Thanks for the PR, @minurmin .  I've assigned this ticket to you and pulled it over to our maintenance board.  I've also added your PR to the list of PRs to be reviewed.
