### ISSUE TITLE
[DS-4086] Error editing users

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7433]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4086">[DS-4086]</a> created by adan.roman</i>
<p>When you click the "select user" button, inside user administration, an internal error es shown.</p>

<p> </p>

<p>2018-11-22 16:37:32,478 ERROR org.dspace.storage.rdbms.DatabaseManager @ SQL query exec Error - <br/>
java.sql.SQLSyntaxErrorException: ORA-00932: tipos de dato inconsistentes: se esperaba - se ha obtenido CLOB</p>

<p>at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)<br/>
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)<br/>
 at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)<br/>
 at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)<br/>
 at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)<br/>
 at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)<br/>
 at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)<br/>
 at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)<br/>
 at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)<br/>
 at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)<br/>
 at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)<br/>
 at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)<br/>
 at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)<br/>
 at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
 at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
 at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
 at org.dspace.storage.rdbms.DatabaseManager.query(DatabaseManager.java:280)<br/>
 at org.dspace.eperson.EPerson.findAll(EPerson.java:518)<br/>
 at org.dspace.app.webui.servlet.admin.EPersonListServlet.doDSGet(EPersonListServlet.java:91)<br/>
 at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:119)<br/>
 at org.dspace.app.webui.servlet.DSpaceServlet.doGet(DSpaceServlet.java:67)</p>

**Comment by tdonohue** [comment]
Closing as Oracle Support was removed in https://github.com/DSpace/DSpace/pull/8822
