### ISSUE TITLE
[DS-4111] NPE in Legacy Rest when loading specific objects

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7458]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4111">[DS-4111]</a> created by terrywbrady</i>
<p>java.lang.NullPointerException<br/>
 at org.dspace.rest.common.Item.setup(Item.java:87)<br/>
 at org.dspace.rest.common.Item.<init>(Item.java:62)<br/>
 at org.dspace.rest.filter.ItemFilterSet.processSaveItems(ItemFilterSet.java:134)<br/>
 at org.dspace.rest.filter.ItemFilterSet.processSaveItems(ItemFilterSet.java:108)<br/>
 at org.dspace.rest.FilteredItemsResource.getItemQuery(FilteredItemsResource.java:134)<br/>
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
 at java.lang.reflect.Method.invoke(Method.java:498)</p>

**Comment by tdonohue** [comment]
Closing, the old (v6) REST API is no longer being actively developed and will be removed in 8.0 (see #7643).  The new REST API v7 is the current REST API: https://github.com/DSpace/RestContract/#readme
