### ISSUE TITLE
[DS-4417] Hibernate Exception when trying to remove Accept/Reject/Edit Metadata Step

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7755]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4417">[DS-4417]</a> created by martin.walk</i>
<p>When I hit the delete button for the Accept/Reject/Edit Metadata Step of a collection in JSPUI I get an internal system error page and the following log entry. I am not able to remove the Step.</p>

<p>I could find one person <a href="http://dspace.2283337.n4.nabble.com/Can-t-delete-Workflow-steps-groups-td4687132.html" class="external-link" target="_blank" rel="nofollow noopener">describing the same problem on a mailing</a> list that was never answered.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-01-13 14:01:34,840 WARN  org.dspace.app.webui.servlet.DSpaceServlet @ admin:session_id=23D4143815A58D0F8FF5AD35EAD3F832:ip_addr=127.0.0.1:general_jspui_error:org.hibernate.ObjectDeletedException\colon; deleted object would be re-saved by cascade (remove deleted object from associations)\colon; [org.dspace.authorize.ResourcePolicy#641593]
org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.dspace.authorize.ResourcePolicy#641593]
	at org.hibernate.internal.SessionImpl.forceFlush(SessionImpl.java:1208)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:184)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
	at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:654)
	at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:646)
	at org.hibernate.engine.spi.CascadingAction$5.cascade(CascadingAction.java:258)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:396)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:339)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:426)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:366)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:342)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:207)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:164)
	at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:165)
	at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:156)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:89)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:61)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1166)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1223)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:171)
	at org.dspace.handle.dao.impl.HandleDAOImpl.getHandlesByDSpaceObject(HandleDAOImpl.java:61)
	at org.dspace.handle.HandleServiceImpl.getInternalHandles(HandleServiceImpl.java:376)
	at org.dspace.handle.HandleServiceImpl.findHandle(HandleServiceImpl.java:279)
	at org.dspace.identifier.VersionedHandleIdentifierProvider.lookup(VersionedHandleIdentifierProvider.java:330)
	at org.dspace.identifier.IdentifierServiceImpl.lookup(IdentifierServiceImpl.java:175)
	at org.dspace.content.DSpaceObjectServiceImpl.getIdentifiers(DSpaceObjectServiceImpl.java:75)
	at org.dspace.content.CollectionServiceImpl.updateLastModified(CollectionServiceImpl.java:899)
	at org.dspace.content.CollectionServiceImpl.updateLastModified(CollectionServiceImpl.java:44)
	at org.dspace.authorize.ResourcePolicyServiceImpl.delete(ResourcePolicyServiceImpl.java:142)
	at org.dspace.authorize.ResourcePolicyServiceImpl.delete(ResourcePolicyServiceImpl.java:33)
	at org.dspace.content.CollectionServiceImpl.setWorkflowGroup(CollectionServiceImpl.java:387)
	at org.dspace.content.Collection.setWorkflowGroup(Collection.java:342)
	at org.dspace.app.webui.servlet.admin.EditCommunitiesServlet.processConfirmEditCollection(EditCommunitiesServlet.java:887)
	at org.dspace.app.webui.servlet.admin.EditCommunitiesServlet.doDSPost(EditCommunitiesServlet.java:274)
	at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:122)
	at org.dspace.app.webui.servlet.DSpaceServlet.doPost(DSpaceServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.app.webui.filter.RegisteredOnlyFilter.doFilter(RegisteredOnlyFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
</pre>
</div></div>
<p> </p>

**Comment by RafaelMansilha** [comment]
Was this solved on DSpace 7.x?

**Comment by tdonohue** [comment]
@RafaelMansilha : I believe this issue only impacts DSpace 6.x, as the code referenced no longer exists in DSpace 7.x (namely the JSPUI no longer exists).
