### ISSUE TITLE
[DS-4436] ORCID - lookup times out

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7773]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4436">[DS-4436]</a> created by hrafn.malmquist</i>
<p>I'm setting up ORCID for the first time on a DSpace 6.3, tomcat is sitting behind Apache HTTPD.</p>

<p>I've followed the instructions in the documentation here: <a href="https://wiki.lyrasis.org/display/DSDOC6x/ORCID+Integration" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.lyrasis.org/display/DSDOC6x/ORCID+Integration</a></p>

<p>When clicking the lookup button the ORCID api is queried by AJAXMenuGenerator but at the end of the call to <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/java/org/dspace/app/xmlui/cocoon/AJAXMenuGenerator.java" class="external-link" target="_blank" rel="nofollow noopener">the generate method </a> a IO Exception is generated see log:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2020-02-18 17:42:17,708 DEBUG org.apache.http.wire @ http-outgoing-37 << "[\r][\n]"
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << HTTP/1.1 200 OK
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Server: nginx/1.16.1
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Cache-Control: no-cache, no-store, max-age=0, must-revalidate
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Content-Type: application/vnd.orcid+xml; qs=5;charset=UTF-8
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Content-Encoding: gzip
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Date: Tue, 18 Feb 2020 17:42:17 GMT
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Expires: 0
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Pragma: no-cache
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << X-XSS-Protection: 1; mode=block
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Transfer-Encoding: chunked
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Access-Control-Allow-Origin: *
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << X-Content-Type-Options: nosniff
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Connection: keep-alive
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << Set-Cookie: X-Mapping-fjhppofk=1F5FD8D0B8B1A8DD0F8680D854A2C10B; path=/
2020-02-18 17:42:17,708 DEBUG org.apache.http.headers @ http-outgoing-37 << X-Frame-Options: DENY
2020-02-18 17:42:17,708 DEBUG org.apache.http.impl.execchain.MainClientExec @ Connection can be kept alive indefinitely
2020-02-18 17:42:17,709 DEBUG org.apache.http.client.protocol.ResponseProcessCookies @ Cookie accepted [X-Mapping-fjhppofk="1F5FD8D0B8B1A8DD0F8680D854A2C10B", version:0, domain:pub.orcid.org, path:/, expiry:null]
2020-02-18 17:42:17,745 DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager @ Connection [id: 37][route: {s}->https://pub.orcid.org:443] can be kept alive indefinitely
2020-02-18 17:42:17,746 DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager @ Connection released: [id: 37][route: {s}->https://pub.orcid.org:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
2020-02-18 17:42:17,746 DEBUG org.dspace.app.xmlui.cocoon.AJAXMenuGenerator @ Result count = 10, default=-1
2020-02-18 17:42:17,747 DEBUG org.hibernate.engine.transaction.spi.AbstractTransactionImpl @ rolling back
2020-02-18 17:42:17,748 DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction @ rolled JDBC Connection
2020-02-18 17:42:17,748 DEBUG org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction @ re-enabling autocommit
2020-02-18 17:42:17,748 DEBUG org.hibernate.engine.jdbc.internal.LogicalConnectionImpl @ Releasing JDBC connection
2020-02-18 17:42:17,748 DEBUG org.hibernate.engine.jdbc.internal.LogicalConnectionImpl @ Released JDBC connection
2020-02-18 17:42:17,748 DEBUG org.dspace.app.xmlui.cocoon.DSpaceCocoonServletFilter @ The connection was reset
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:333)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:758)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:287)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:261)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:498)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
	at org.apache.cocoon.servletservice.HttpServletResponseBufferingWrapper.flushBufferedResponse(HttpServletResponseBufferingWrapper.java:240)
	at org.apache.cocoon.servletservice.ServletServiceContext$PathDispatcher.forward(ServletServiceContext.java:481)
	at org.apache.cocoon.servletservice.ServletServiceContext$PathDispatcher.forward(ServletServiceContext.java:443)
	at org.apache.cocoon.servletservice.spring.ServletFactoryBean$ServiceInterceptor.invoke(ServletFactoryBean.java:264)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy161.service(Unknown Source)
	at org.dspace.springmvc.CocoonView.render(CocoonView.java:113)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1216)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1001)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.app.xmlui.cocoon.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.app.xmlui.cocoon.DSpaceCocoonServletFilter.doFilter(DSpaceCocoonServletFilter.java:160)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.app.xmlui.cocoon.servlet.multipart.DSpaceMultipartFilter.doFilter(DSpaceMultipartFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:394)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1223)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:743)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:696)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:686)
	at org.apache.coyote.ajp.AjpProcessor.writeData(AjpProcessor.java:1197)
	at org.apache.coyote.ajp.AjpProcessor.access$600(AjpProcessor.java:53)
	at org.apache.coyote.ajp.AjpProcessor$SocketOutputBuffer.doWrite(AjpProcessor.java:1269)
	at org.apache.coyote.Response.doWrite(Response.java:599)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:328)
	... 57 more

</pre>
</div></div>

<p>Apache will then return a 502 error screen.</p>

<p>Even more confusingly, the exception isn't visible in the logs unless logging level is set to debug. If it's set to info only a ClientConnection error is logged.<br/>
ERROR org.dspace.app.xmlui.cocoon.DSpaceCocoonServletFilter @ Client closed the connection before file download was complete</p>

<p>The URL that's being retrieved is /choices/dc_contributor_author?query=AUTHOR-NAME&collection=52d9c825-95c0-45c2-b687-ca3505eb743b&start=0&limit=10&_=1582047703416</p>

<p>If I manually change limit to a lower number the query returns ok. But this prevents the lookup popup window from functioning.</p>

**Comment by tdonohue** [comment]
Closing, as this has had no recent activity and appears to be more of a support question.  It this is a bug that still exists we can reopen at a later date.
