### ISSUE TITLE
External Source Entry ID should be more flexible?

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#7944]
**Describe the bug**
 to obtain an entry value ([single entry](https://github.com/DSpace/RestContract/blob/main/external-authority-sources.md#single-entry)), you should provide an **entry id**, like:

```
GET /api/integration/externalsources/<:source-name>/entryValues/<:entry-id>
```

to me that `entry id` could be any alphanumeric string, but can also be an URL, URN or URI (something that univocally differentiates that entry within the source context). The issue it's that you can't define/use an `entry-id` that has/uses slashes (/).

**To Reproduce**
Currently, to obtain an orcid source single entry, the endpoint is:
```
/api/integration/externalsources/orcid/entryValues/0000-0002-4271-0436
```

it was defined `0000-0002-4271-0436` as the `entry id`. But to understand the issue, imagine that your source uses URLs like `https://orcid.org/0000-0002-4271-0436`, then your endpoint would be:
```
/api/integration/externalsources/orcid/entryValues/https://orcid.org/0000-0002-4271-0436
```
but when this URL is parsed, it won't be mapped into any controller, doesn't know what to do. And an info message is posted to log:
```
2021-09-15 12:55:34,544 INFO  unknown b039d651-6eee-4947-a91b-49b07814aa91 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/integration/externalsources/orcid/entryValues/https:/orcid.org/0000-0002-4271-0436] originated from unknown
```
You can also simulate encoding the `https://orcid.org/0000-0002-4271-0436` URL.
```
/api/integration/externalsources/orcid/entryValues/https%3A%2F%2Forcid.org%2F0000-0002-4271-0436
```
but you will get an 400 error 
```
HTTP Status 400 – Bad Request

Type Status Report

Message Invalid URI: noSlash

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
Apache Tomcat/9.0.30
```

You can try a double encoding. Then your URL would be: https%253A%252F%252Forcid.org%252F0000-0002-4271-0436
```
/api/integration/externalsources/orcid/entryValues/https%253A%252F%252Forcid.org%252F0000-0002-4271-0436
```
and if you try to execute it, you will have a spring security exception for trying to use `%25`.

```
2021-09-15 13:18:59,020 ERROR unknown unknown org.springframework.boot.web.servlet.support.ErrorPageFilter @ Forwarding to error page from request [/api/integration/externalsources/orcid/entryValues/https%3A%2F%2Forcid.org%2F0000-0002-4271-0436] due to exception [The request was rejected because the URL contained a potentially malicious String "%25"]
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "%25"
        at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:369) ~[spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:336) ~[spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:194) ~[spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.30]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.30]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.30]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.30]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.30]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.13.3.jar:2.13.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.30]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.30]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.30]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.30]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.30]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.30]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.30]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.30]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.30]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-coyote.jar:9.0.30]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.30]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-coyote.jar:9.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) [tomcat-coyote.jar:9.0.30]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.30]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Expected behavior**
I expected for `entry-id` to be more loose and flexible. And when external sources methods to support string URL encoding in order to escape these kind of errors.

**Related work**
https://github.com/DSpace/DSpace/pull/3365

**Comment by paulo-graca** [comment]
I think a possible solution for it could be base64 encoding and decoding when setting and getting IDs

```
public class ExternalDataObject {

    /**
     * Generic setter for the ID
     * @param id    The id to be set
     */
    public void setId(String id) {
        this.id = Base64.getEncoder().encodeToString(id.getBytes());
    }


    /**
     * Generic getter for the ID
     * @return  The id
     */
    public String getId() {
        return new String(Base64.getDecoder().decode(id));
    }

```

**Comment by tdonohue** [comment]
@paulo-graca : I definitely understand how this might be an improvement conceptually.  However, do you have any examples of where an entry ID _would often not be an alphanumeric string_? 

The reason I ask is that, in each External Source Provider instance, we get to essentially "choose" what to return as the Entry ID (as long as we know it's a unique way to lookup that Entry later with the same provider).  So, if a specific External Source Provider returned a full URL as the ID (like "https://orcid.org/0000-0002-4271-0436"), we could choose a few options:
* We could strip down the URL to something unique (in this case we know this is an ORCID and can transform it into "0000-0002-4271-0436"). 
* Or, as you noted, we could choose to Base-64 encode that _in that Provider instance_ 

My concern here is that I'm not sure whether we need to base-64 encode all IDs from all External Sources at all times (which may not be necessary, unless we find this is a common issue across all providers).   If we find only a few providers return IDs which are not alphanumeric, then we can base-64 encode them in the provider code itself.

**Comment by paulo-graca** [comment]
I choose to use the ORCID example to better explain the error. A real occurrence of this issue it's with OpenAIRE project identifier using OpenAIRE 3.0 Guidelines - https://guidelines.openaire.eu/en/latest/literature/field_projectid.html or with any other identifier that needs to be escaped from the URL.
I found this issue when developing OpenAIRE tests and didn't understand why didn't fail earlier at the frontend. Until I realize that the angular inferface wasn't requesting the `/api/integration/externalsources/<source>/entryValues/<entry-id>` endpoint.
My request URL would be something like:
```
/api/integration/externalsources/openaireFunder/entryValues/info:eu-repo/grantAgreement/EC/FP7/244909/EU/Making Capabilities Work/WorkAble
```

the `entry-id` it's only used in the scope of external sources requests, changing it, ensuring that requesting the detail page from the source is performed the same way, doesn't affect the functionality and ensures we can have any kind of `entry-id`.

To fix my issue I choose to use base64 encoding at my set id level implementation, but I think using it sitewide, every implementation would benefit from it. This change would not have any implication on the Angular side.

**Comment by paulo-graca** [comment]
I still consider the issue relevancy. Of course this doesn't apply to the majority of the external sources, but some, where we have a composed ID (the ID is split in parts) might benefit from it.
