### ISSUE TITLE
IllegalArgumentException when sorting metadata in DSpaceObjectServiceImpl

### ISSUE THREAD

**Issue by tysonlt** [DSpace/DSpace#7982]
**Describe the bug**
When adding metadata with relationships, the sort method in DSpaceObjectServiceImpl.java:623 is occasionally throwing an IllegalArgumentException:

`java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
        at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
        at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
        at java.base/java.util.TimSort.sort(TimSort.java:254)
        at java.base/java.util.Arrays.sort(Arrays.java:1515)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
        at org.dspace.content.DSpaceObjectServiceImpl.update(DSpaceObjectServiceImpl.java:623)
        at org.dspace.content.ItemServiceImpl.update(ItemServiceImpl.java:496)
        at org.dspace.content.ItemServiceImpl.update(ItemServiceImpl.java:71)
        at org.dspace.content.RelationshipServiceImpl.updateItem(RelationshipServiceImpl.java:186)
        at org.dspace.content.RelationshipServiceImpl.updateItemsInRelationship(RelationshipServiceImpl.java:425)
        at org.dspace.content.RelationshipServiceImpl.create(RelationshipServiceImpl.java:102)
        at org.dspace.content.RelationshipServiceImpl.create(RelationshipServiceImpl.java:89)
        at org.dspace.content.RelationshipServiceImpl.create(RelationshipServiceImpl.java:72)`

**To Reproduce**
This occurs occasionally when adding relationships during import. I am currently tracking down exactly which item causes the problem, but it might be a bit hard to reproduce.

The relevant code is:

`            
            metadataValues.sort(new Comparator<MetadataValue>() {
                @Override
                public int compare(MetadataValue o1, MetadataValue o2) {
                    int compare = o1.getPlace() - o2.getPlace();
                    if (compare == 0) {
                        if (o1 instanceof RelationshipMetadataValue) {
                            return 1;
                        } else if (o2 instanceof RelationshipMetadataValue) {
                            return -1;
                        }
                    }
                    return compare;
                }
            });
`

It may be occurring when both o1 and o2 are RelationshipMetadataValue objects? In this case, should the method return 0?

**Comment by tysonlt** [comment]
It seems to be fixed by adding -Djava.util.Arrays.useLegacyMergeSort=true to JAVA_OPTS

**Comment by tdonohue** [comment]
It sounds like this is a bug and the Comparator isn't valid based on the description at https://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html#compare(T,%20T)  Flagging this as high priority to fix, as otherwise this could result in odd behavior.
