### ISSUE TITLE
Creative common licence step not loading

### ISSUE THREAD

**Issue by MarisArins** [DSpace/DSpace#7991]
When enabling <step id="cclicense"/> in item-submission.xml configuration, CC licence segment does not appear on submission form.

If a DEBUG level I can see that CC Licence step got prepared : 
`[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfigReader - Submission process config has 2 steps listed.
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfigReader - Loading submission process config named 'Publication'
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfigReader - Submission process config 'Publication' not in cache. Reloading from scratch.
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.CollectionStep' as step #0 of submission process Publicat                 ion
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.DescribeStep' as step #1 of submission process Publicatio                 n
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.DescribeStep' as step #2 of submission process Publicatio                 n
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.UploadStep' as step #3 of submission process Publication
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.CCLicenseStep' as step #4 of submission process Publicati                 on
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfig - Added step 'org.dspace.app.rest.submit.step.LicenseStep' as step #5 of submission process Publication
[DEBUG] 2021-10-11 19:08:42.833 [https-openssl-apr-8443-exec-3] SubmissionConfigReader - Submission process config has 6 steps listed.
`

Bit later code prints out an Exception related to CC Licence :
`[ERROR] 2021-10-11 19:34:34.756 [https-openssl-apr-8443-exec-9] AInprogressItemConverter - An error occurred during the unmarshal of the data for the section cclicense - reported error: null
java.lang.NullPointerException: null
	at org.dspace.app.rest.converter.ConverterService.toRest(ConverterService.java:107) ~[classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.submit.SubmissionService.getDataCCLicense(SubmissionService.java:307) ~[classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.submit.step.CCLicenseStep.getData(CCLicenseStep.java:41) ~[classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.submit.step.CCLicenseStep.getData(CCLicenseStep.java:26) ~[classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.converter.AInprogressItemConverter.fillFromModel(AInprogressItemConverter.java:105) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.converter.WorkspaceItemConverter.convert(WorkspaceItemConverter.java:35) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.converter.WorkspaceItemConverter.convert(WorkspaceItemConverter.java:23) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.converter.ConverterService.toRest(ConverterService.java:108) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.repository.WorkspaceItemRestRepository.findOne(WorkspaceItemRestRepository.java:137) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.repository.WorkspaceItemRestRepository.findOne(WorkspaceItemRestRepository.java:75) [classes/:7.1-SNAPSHOT]
	at org.dspace.app.rest.repository.WorkspaceItemRestRepository$$FastClassBySpringCGLIB$$987ae76d.invoke(<generated>) [classes/:7.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]`

In result CC Licence step is not appearing on submission form

Strange is that submission process calls "AInprogressItemConverter" and code expects a CC Licence values to be present in fresh Item object metadata.

**Comment by tdonohue** [comment]
@MarisArins : I'm able to reproduce this as well.  I cannot get the CC License step to load.  Moving this to our 7.2 board & flagging as high priority.

**Comment by g011um** [comment]
Sorry I have nothing to contribute other than a "me too".  We're in the process of moving from 6.x to 7.x and are seeing this same "`An error occurred during the unmarshal of the data for the section cclicense`" error with a fresh install of 7.2.1 after enabling the `cclicense` step.
