### ISSUE TITLE
Virus Scan Curation task fails on document upload.

### ISSUE THREAD

**Issue by firoball** [DSpace/DSpace#8139]
**Describe the bug**
This is a takeover from discussion in Google group: https://groups.google.com/g/dspace-tech/c/Z10Z4IIfqho/m/8-RZXk1yAgAJ

Enabling clamAV virus scan in curate.cfg (as per guide in Wiki) causes document upload to fail as soon as a review group is configured for the selected collection.
According to the analysis in the linked discussion the virus scan tries to access a bitstream without having sufficient rights.

**To Reproduce**
1. Make sure the collection of choice has a at least a review group assigned
2. Make sure virus scan task is enabled in curate.cfg

```
plugin.named.org.dspace.curate.CurationTask = org.dspace.ctask.general.ClamScan = vscan
curate.ui.tasknames = vscan = Virus Scan

```
3. Add new item with attachment to the colelction and hit "Deposit" button.

Reduced error message (full one is in group discussion):
```
Caused by: java.io.IOException: Authorization denied for action READ on BITSTREAM:cad9f343-6588-4a5f-a7a6-8acc996f58ef by user null
        at org.dspace.ctask.general.ClamScan.perform(ClamScan.java:125) ~[dspace-api-7.1.1.jar:7.1.1]
        at org.dspace.curate.ResolvedTask.perform(ResolvedTask.java:79) ~[dspace-api-7.1.1.jar:7.1.1]
        at org.dspace.curate.Curator$TaskRunner.run(Curator.java:547) ~[dspace-api-7.1.1.jar:7.1.1]
        at org.dspace.curate.Curator.curate(Curator.java:275) ~[dspace-api-7.1.1.jar:7.1.1]
Caused by: org.dspace.authorize.AuthorizeException: Authorization denied for action READ on BITSTREAM:cad9f343-6588-4a5f-a7a6-8acc996f58ef by user null
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:166) ~[dspace-api-7.1.1.jar:7.1.1]
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:114) ~[dspace-api-7.1.1.jar:7.1.1]
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:108) ~[dspace-api-7.1.1.jar:7.1.1]
```

In the discussion also workflow-curation.xml with a change for attaching curation taks to workflow steps was addressed. However even disabling the "cautious" taskset and replacing it with default setting does not change the described behaviour.
Only reverting curate.cfg and disabling clamAV integration helps avoiding the exception.

**Expected behavior**
No exception happens, item submission is successful, workflow can continue as regular.

**Related work**
https://groups.google.com/g/dspace-tech/c/Z10Z4IIfqho/m/8-RZXk1yAgAJ

**Comment by firoball** [comment]
It turns out my description is not fully accurate. For some reason I need to restart Tomcat after changing curate.cfg, auto reload won't work in this case.
I missed that and therefore my previous description is a bit off. The real culprit is - and now it also makes some sense - workflow-curation.xml and not curate.cfg.

Adding in the contents of this file, resulting in the above issue:

```
<?xml version="1.0" encoding="UTF-8" ?>
<workflow-curation xmlns='https://dspace.org/workflow-curation'>

 <taskset-map>
   <mapping collection-handle="default" taskset="cautious" />
 </taskset-map>

 <tasksets>

   <taskset name="cautious">
     <flowstep name="step1">
       <task name="vscan">
         <workflow>reject</workflow>
         <notify on="fail">$flowgroup</notify>
         <notify on="fail">$colladmin</notify>
         <notify on="error">$siteadmin</notify>
       </task>
     </flowstep>
   </taskset>

    <!-- We require an empty taskset to match "none" mappings.  DO NOT REMOVE! -->
    <taskset name='none'/>

```

**Comment by tdonohue** [comment]
This ticket and #8169 are the same issue.  I'm closing this ticket in favor of #8169, simply because that ticket has slightly more activity/planning.
