### ISSUE TITLE
Special groups not working with Shibboleth authentication

### ISSUE THREAD

**Issue by mspalti** [DSpace/DSpace#8161]
**Describe the bug**
Cannot access content that is restricted to a special group. When using Shibboleth authentication special groups are created at login but are not used for subsequent requests.

**To Reproduce**
1. Configure Shibboleth and Shibboleth roles for special groups
2. Restrict Item read access to a special group
3. Log in and attempt to view the content

**Expected behavior**
Obviously you would expect to see the item if you are a member of the special group.

**Related work**
#8160

**Comment by samj55** [comment]
I think this bug still exist. Please double check.

DSpace version installed:  DSpace 7.3-SNAPSHOT

To repreduce:

1. Create a new Community. Edit Authorizations and restrict read access to Shibboleth Special Group
2. Create a new collection. Edit Assign Roles and restrict BITSTREAM_DEFAULT_READ and DEFAULT_READ and finally add Shibboleth Special Group as a subgroup to both groups you just created.
3. For the same collection Edit Authorizations and restrict the read access to Shibboleth Special Group
4. Ingest/import a new item.
5. Login as Shibboleth user. You will see the Shibboleth Special Group is listed in the user profile and the restricted item is visible but viewing the bitstream will develop the error you see in the log below. ( I think IP Authentication is also having the same issue ).

dspace.log shows:
java.io.IOException: org.dspace.authorize.AuthorizeException: Authorization denied for action READ on BITSTREAM:549dad0f-2438-41c0-ad1c-d1ebfc8ca982 by user 1ccce6d2-beaf-43cc-8b64-b9a15a30e62e
        at org.dspace.app.rest.utils.BitstreamResource.getInputStream(BitstreamResource.java:102) ~[classes/:7.3-SNAPSHOT]
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:137) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:129) ~[spring-web-5.3.18.jar:5.3.18]
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:45) ~[spring-web-5.3.18.jar:5.3.18]
