### ISSUE TITLE
"./dspace solr-reindex-statistics" doesn't work in DSpace 7.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8181]
**Describe the bug**
Reported on behalf of this thread: https://groups.google.com/g/dspace-community/c/xguccnJkrJM/m/UxcRrjcKBwAJ

The `./dspace solr-reindex-statistics` script is broken in DSpace 7 because it attempts to access the Solr data in the old DSpace 6.x directory structure (instead of using SOLR_DATA_HOME or similar).

When running it in DSpace 7, you will receive an error similar to this:
```
# ./dspace solr-reindex-statistics
No index name provided, defaulting to "statistics".
Exception: Error from server at http://localhost:8983/solr: Path /dspace7/solr/statistics must be relative to SOLR_HOME, SOLR_DATA_HOME coreRootDirectory. Set system property 'solr.allowPaths' to add other allowed paths.
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr: Path /dspace7/solr/statistics must be relative to SOLR_HOME, SOLR_DATA_HOME coreRootDirectory. Set system property 'solr.allowPaths' to add other allowed paths.
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:231)
        at org.dspace.util.SolrImportExport.reindex(SolrImportExport.java:320)
        at org.dspace.util.SolrImportExport.main(SolrImportExport.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```

The problem appears to be in this line of code, which still expects the Solr instance to be relative to `dspace.dir`: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/util/SolrImportExport.java#L255-L256

**Expected behavior**
Either this script should work again, or we should document another way to perform the same `reindex` task.

**Comment by ammanabrolua** [comment]
Can we add a separate way to add the SOLR path in local.cfg file? Like -> `solr.path='/opt/bin/solr'`. This will be quick solution but will have to be documented as you mentioned.

**Comment by tdonohue** [comment]
@ammanabrolua : Yes, I think that'd be a perfectly reasonable solution to make the directory configurable in your `local.cfg`.  If you are interested in making this happen, I'd welcome it.  Just submit a Pull Request & link it back to this ticket, at which point I'll help find reviewers and hopefully we can get this into 7.3.  Thanks!

**Comment by mwoodiupui** [comment]
Notice that the suggested approach works *only* if Solr and DSpace are on the same host.  The general solution would be to ask Solr for the core's instance directory, e.g. "GET http://solr-host.example.com:8983/api/cores" and pick status.[corename].instancedir out of the returned JSON document.

**Comment by nwoodward** [comment]
I looked at this a bit, and @mwoodiupui is correct that the instanceDir can be obtained from the JSON status response. 
> Object solrInstanceDirObj = status.getCoreStatus(instanceIndexName).get("instanceDir");

But there's another issue with the data directory used for the temporary core. I'm still researching how that could be handled in a Solr instance that's on a different server than DSpace.
https://github.com/DSpace/DSpace/blob/ccd47b0ddd2df3cf7560678e29d5311e7e866ea2/dspace-api/src/main/java/org/dspace/util/SolrImportExport.java#L300-L318

**Comment by cpgray** [comment]
Did a solr.path setting ever get added to local.cfg? It doesn't seem to work in our 7.6.2 instance. This ticket seems to have wandered away from its original purpose.
