### ISSUE TITLE
GoogleBitstreamComparator - Comparison method violates its general contract

### ISSUE THREAD

**Issue by ulb-sa-schmilj** [DSpace/DSpace#8211]
**Describe the bug**
GoogleBitstreamComparator - Comparison method violates its general contract

**To Reproduce**
1. Submit a new item. With many/more than 10 files/bitstreams with the same file extension and the same size.
2. The following Exception is thrown:
`java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
        at java.util.TimSort.sort(TimSort.java:254)
        at java.util.Arrays.sort(Arrays.java:1438)
        at java.util.List.sort(List.java:478)
        at java.util.Collections.sort(Collections.java:175)
        at org.dspace.app.util.GoogleMetadata.findLinkableFulltext(GoogleMetadata.java:1054)
        at org.dspace.app.util.GoogleMetadata.getPDFSimpleUrl(GoogleMetadata.java:1008)
        at org.dspace.app.util.GoogleMetadata.addSingleField(GoogleMetadata.java:259)`

In our submission we have many scans of a book (TIFFs) with the same resolution. -> Uncompressed TIFF, same resolution -> same file size.

**Expected behavior**
A compare method that not violates the contract. 

`
 public int compare(Bitstream b1, Bitstream b2) {
        int priority1 = getPriorityFromBitstream(b1);
        int priority2 = getPriorityFromBitstream(b2);

        if (priority1 > priority2) {
            return 1;
        } else if (priority1 == priority2) {
            if (b1.getSizeBytes() <= b2.getSizeBytes()) {
                return 1;
            } else {
                return -1;
            }
        } else {
            return -1;
        }
    }
`

bitstream1, bitstream2 have the same file size and the same extension (priority1 == priority2 is true).
The method say for: 
 - compare(bitstream1, bitstream2) -> 1
 - compare(bitstream2, bitstream1) -> also 1
This is a violation.

The bug is found in the code of DSpace 6.x, but I think there is also a copy of the code in DSpace 7.x.

**Comment by tdonohue** [comment]
Thanks @ulb-sa-schmilj !  This was a small fix, so I went ahead and created a tiny PR https://github.com/DSpace/DSpace/pull/8212   If you have a chance to review or try it out, please feel free to add a comment on what you find.
