### ISSUE TITLE
Harvesting into collection doesn't work (Xalan missing)

### ISSUE THREAD

**Issue by milanmajchrak** [DSpace/DSpace#8347]
**Describe the bug**
DSpace Docker container version: dspace-7_x

The command `/dspace/bin/dspace harvest` doesn't work in the Docker.  
It throws exception: 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xpath/XPathAPI
        at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:295)
        at ORG.oclc.oai.harvester2.verb.HarvesterVerb.getSingleString(HarvesterVerb.java:281)
        at ORG.oclc.oai.harvester2.verb.HarvesterVerb.harvest(HarvesterVerb.java:262)
        at ORG.oclc.oai.harvester2.verb.HarvesterVerb.<init>(HarvesterVerb.java:183)
        at ORG.oclc.oai.harvester2.verb.Identify.<init>(Identify.java:48)
        at org.dspace.harvest.HarvestedCollectionServiceImpl.verifyOAIharvester(HarvestedCollectionServiceImpl.java:200)
        at org.dspace.app.harvest.Harvest.pingResponder(Harvest.java:445)
        at org.dspace.app.harvest.Harvest.internalRun(Harvest.java:238)
        at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104)
        at org.dspace.app.launcher.ScriptLauncher.executeScript(ScriptLauncher.java:149)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:131)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
Caused by: java.lang.ClassNotFoundException: org.apache.xpath.XPathAPI
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 12 more

_XPathAPI_ class should be in the _xalan-2.7.0.jar_ but this .jar is missing in the  _docker-cli_ image.

**To Reproduce**
1. docker pull dspace/dspace:dspace-7_x
2. docker run dspace/dspace:dspace-7_x
3. docker exec -it <CONTAINER_ID> /bin/bash
4. go to _/dspace/bin_
5. run command: `./dspace harvest -g -a http://lindat.mff.cuni.cz/repository/oai/request -i hdl_11234_3430`

**Expected behavior**
Start harvesting or throw error that Database or Solr is not working.

**Related work**

**Comment by tdonohue** [comment]
I've verified this bug exists on `main`.  It appears the `ORG.oclc.oai.harvester2.*` classes used by DSpace in this area **do depend heavily on Xalan** which was removed in #8258 .

I'll create a PR to add Xalan back in until we can fix this dependency in the OCLC OAI Harvester codebase.
