### ISSUE TITLE
DSpace (5/6?) handle server doesn't start after JDK 8 update

### ISSUE THREAD

**Issue by OyvindLGjesdal** [DSpace/DSpace#8557]
**Describe the bug**
After updating to
```
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```
or 
```
openjdk version "1.8.0_352"
OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM Corretto-8.352.08.1 (build 25.352-b08, mixed mode)
```

The handle-server script no longer starts, probably due to [JDK-8287132 - Retire Runtime.runFinalizersOnExit so that it always throws UOE](https://bugs.openjdk.org/browse/JDK-8287132)

**To Reproduce**
1. Update the system packaged JDK 8 (Coretto and RHEL-packaged openjdk confirmed)
2. Try to start handle-server script
3. (Startup error message)

```
2022/10/26 03:04:46 CEST" 25 Started new run.
java.lang.UnsupportedOperationException
    at java.lang.Runtime.runFinalizersOnExit(Runtime.java:287)
    at java.lang.System.runFinalizersOnExit(System.java:1059)
    at net.handle.server.Main.initialize(Main.java:124)
    at net.handle.server.Main.main(Main.java:75)
Shutting down...
````

The reported errors in the mailing lists looks like DSpace 5 installations, but the handle server dependency looks the same in the DSpace 6 pom.xml, so probably also applies there?

**Expected behavior**

Normal startup of handle-server

**Related work**
https://bugs.openjdk.org/browse/JDK-8287132
https://groups.google.com/g/dspace-community/c/B-865GtF93A

**Comment by tdonohue** [comment]
This seems like the same issue we saw with JDK11 + DSpace 5/6. See #7892.   It's frustrating that JDK8 seems to have broken their own backwards compatibility.

The fix for that in DSpace 7 was to upgrade to using Handle Server v9 via #2828 and #2907.   It might be possible to backport these PRs to DSpace 5 & 6 (I haven't had a chance to look into it yet).  If anyone has time to try this backport, please let us know how it goes!  I'm hopeful maybe it won't be too painful of a backport.

**Comment by OyvindLGjesdal** [comment]
@tdonohue I could try getting it to work for clarin-dspace and then add a similar PR for the dspace 5 and 6 branches but I'm unsure how to test if it works.

I have managed to build with the [PR for clarin-dspace](https://github.com/ubbdst/clarin-dspace/commit/dd37d977e4ee259fc571f662b83ef79f3b52df39) which looks similar to your PRs above, and to test it out I tried to use the dspace bin for configuring a handle-server.

``` 
 bin/dspace make-handle-config /dspace/build/handle-server
```
I can fill in the blanks and complete it, but I get the warning:
```
WARNING: Error adding admin.war to server:
java.io.FileNotFoundException: /dspace/clarino/build/admin.war (No such file or directory)
You will have to add admin.war to the webapps subdirectory manually.
```
Is this something which should be looked at?

I'm unsure how to test if the handle-server works, without configuring a real handle, or *testing on prod* which I would prefer not to do.

**Comment by tdonohue** [comment]
@OyvindLGjesdal :  Thanks for your feedback.  After digging around a bit, I realized that there was some earlier work also needed to support migrating to Handle Server v9 in #2394 ... and those changes involved minor updates to the `make-handle-config` script.  Maybe that's the missing piece here?  I'd recommend trying to make those updates to `make-handle-config` and trying again...hopefully it'll work this time.

In terms of testing the handle-server works, you should be able to minimally start the handle-server with some "fake/test" settings, and verify that it starts up on the configured ports (2641 and 8000 by default, IIIRC).

In any case, if you can get `dspace make-handle-config` to no longer throw errors, and `start-handle-server` to spin everything up on the expected ports, then that should mean that everything is "working".  At that point, if you wanted to create a PR, then I'm sure we could find some testers to help verify it works for them.

**Comment by OyvindLGjesdal** [comment]
I can now build the handle-server for the clarin-dspace fork, unfortunately several other depencies had to be bumped.

https://github.com/ufal/clarin-dspace/pull/1021/files

Some notable things:
*  The jetty dependency failed when using the old gson (and excluding it from jetty)
```
Exception in thread "Thread-3" java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
        at net.handle.hdllib.trust.JsonWebSignatureImpl.getAlgStringFromHeader(JsonWebSignatureImpl.java:95)
        at net.handle.hdllib.trust.JsonWebSignatureImpl.<init>(JsonWebSignatureImpl.java:88)
        at net.handle.hdllib.trust.JsonWebSignatureFactoryImpl.deserialize(JsonWebSignatureFactoryImpl.java:30)
        at net.handle.hdllib.trust.HandleRecordTrustVerifier.getJsonWebSignaturesFromValues(HandleRecordTrustVerifier.java:129)
        at net.handle.hdllib.trust.HandleRecordTrustVerifier.validateHandleRecordReturnReport(HandleRecordTrustVerifier.java:65)
        at net.handle.hdllib.trust.HandleRecordTrustVerifier.validateHandleRecord(HandleRecordTrustVerifier.java:47)
        at net.handle.hdllib.Configuration.resolveVerifyUpdateAndPersistBootstrapHandles(Configuration.java:216)
        at net.handle.hdllib.Configuration.refreshRootInfoFromNet(Configuration.java:183)
        at net.handle.hdllib.Configuration.access$000(Configuration.java:29)
        at net.handle.hdllib.Configuration$2.run(Configuration.java:314)
```
* xmlui build fails when pulling in dspace-api dependency when jetty dependency is present. ( we don't build all modules, the same could be true for other modules which depend on dspace-api.
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dspace-xmlui: Compilation failure
[ERROR] /dspace/clarino/source/dspace-xmlui/src/main/java/org/dspace/app/xmlui/cocoon/HttpServletRequestCocoonWrapper.java:[44,8] org.dspace.app.xmlui.cocoon.HttpServletRequestCocoonWrapper is not abstract and does not override abstract method <T>upgrade(java.lang.Class<T>) in javax.servlet.http.HttpServletRequest
```

* the bouncyapi dependencies had to be updated to the new `on` package to get the handle-server to run
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/x500/X500Name
        at net.handle.util.X509HSCertificateGenerator.generateWithCnAndUid(X509HSCertificateGenerator.java:91)
        at net.handle.util.X509HSCertificateGenerator.generateWithUid(X509HSCertificateGenerator.java:83)
        at net.handle.util.X509HSCertificateGenerator.generate(X509HSCertificateGenerator.java:56)
        at net.handle.server.HandleServer.buildCertificate(HandleServer.java:222)
        at net.handle.server.HandleServer.initKeysAndCertsAndSignatures(HandleServer.java:522)
        at net.handle.server.HandleServer.<init>(HandleServer.java:366)
        at net.handle.server.AbstractServer.getInstance(AbstractServer.java:120)
        at net.handle.server.Main.initialize(Main.java:255)
        at net.handle.server.Main.main(Main.java:122)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.x500.X500Name
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 9 more
```
* On first (working startup) I got the message in the handle error-log:

```
"2022-11-04 20:54:57.465+0100" 25 Handle.net Server Software version 9.3.0
Saving bootstrap handles to: /home/tomcat/.handle/bootstrap_handles
```

Attached the full log from the handle-server error log, which led to the handle upgrades.
[error.log](https://github.com/DSpace/DSpace/files/9953120/error.log)

**Comment by tdonohue** [comment]
@OyvindLGjesdal : Thanks for the updates.  It sounds, to me, like this upgrade to Handle Server v9.x may not be fully possible for the DSpace 6.x codebase then?  Obviously, we cannot do this upgrade if it breaks the entire XMLUI (as that would impact roughly 50% of all 6.x sites, since it's about a 50%/50% split between JSPUI and XMLUI).

**Comment by OyvindLGjesdal** [comment]
I was a bit unclear above I see.

xmlui builds and works(?) if I exclude some artifacts from the dspace-api dependency from `dspace-xmlui/pom.xml`

```
  <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-api</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.cnri</groupId>
                    <artifactId>cnri-servlet-container</artifactId>
                </exclusion>
            </exclusions>
```

I saw that `dspace-api`  is a dependency for other modules that we don't use, so other artifacts could also have issues with the updated dependencies (and need exclusions?)

I'll try to get a PR for the dspace 6 branch

**Comment by tdonohue** [comment]
@OyvindLGjesdal : Ok, thanks for clarifying.  Yes, please do create a PR against the `dspace-6_x` branch... that way we should be able to find others to help test this work & verify whether it's a full fix, or if there's additional code changes we necessary. I appreciate all the work you've done so far. I think it'll be easiest for myself & others to help you out if you can create a PR. Thanks!

**Comment by OyvindLGjesdal** [comment]
Our fork where I managed to start the handle-server, is a Dspace 5 fork.

DSpace 6 github actions is stopped by the enforcer plugin, while I don't think DSpace 5 uses it?

**Comment by ebalnaves** [comment]
I have tested a working alternative by rebuilding handle-6.2.jar with a minor change to ./net/handle/server/Main.java to comment out the now discontinued class at line 124
//System.runFinalizersOnExit(true);

Rebuild the handle jar and replace.  Handle server starts successfully and tested with a handle lookup.

Could provide alternative for some to get a server live.

Happy to share the build to project the above jar and/or the jar itself

Gives us a fall-back solution at least.

**Comment by tdonohue** [comment]
@ebalnaves : If you could either share the updated `handle-6.2.jar` or link us directly to the Handle server code you downloaded & changed, that'd be appreciated.  I agree that this might provide an alternative, perhaps easier, solution to those who are impacted.

**Comment by ebalnaves** [comment]
I have shared the test source at https://release.prosentient.com.au/handle62/handle6.2patched.tar.gz

The base is hdl 6.2.05 code from handle.net 

Note that this does not contain the cnriutil references.

I compiled lib/cnriutil.jar derived from the classes in the dspace version of handle-6.2.jar

To achieve a distribution I modified the build.xml to remove references to the admintools.  I'm guessing this must have been done before with the dspace distro.

I modified 
 ./net/handle/server/Main.java 
 to remove System.runFinalizersOnExit(true);

Further work could be done to replace this with an alternative code
	Runtime.addShutdownHook(new Runnable() {
		public void run(){
			// do whatever handle.net needs to exit cleaning on error();
		}
	});

However I have tested the above simple change successfully in an updated ubuntu server running the dspace handle resolver.  
Not tested for long term service operation, so there is a risk the above change might lead to some memory leakage.  However the fact that the handle service runs seperately makes it easy to monitor.

The build process is:
 ant clean
 ant server
 ant distjar

The build output is in the dist folder

Hope this helps.

Edmund

**Comment by ebalnaves** [comment]
The compiled handle.jar file is available at https://release.prosentient.com.au/handle62/handle.jar.gz
It can be used to replace the handle-6.2.jar reference in the dspace 6.4 build or copied directly to the target directly to the target directories - particularly of course lib

./lib/handle-6.2.jar
./webapps/jspui/WEB-INF/lib/handle-6.2.jar
./webapps/xmlui/WEB-INF/lib/handle-6.2.jar
./webapps/swordv2/WEB-INF/lib/handle-6.2.jar
./webapps/rdf/WEB-INF/lib/handle-6.2.jar
./webapps/rest/WEB-INF/lib/handle-6.2.jar
./webapps/sword/WEB-INF/lib/handle-6.2.jar
./webapps/oai/WEB-INF/lib/handle-6.2.jar

It was an interesting archeological exercise obtaining the handle v6 source.  handle.net do not maintain web references to archived distributions.   web.archive.org was helpful in this respect

Edmund

**Comment by OyvindLGjesdal** [comment]
I don't know much about different java distros but https://www.azul.com/downloads/?package=jdk looks like it has LTS for Java 1.7? Could be listed as a maintained alternative?

**Comment by tdonohue** [comment]
@OyvindLGjesdal :  Yes, using Azul Zulu's version of JDK 1.7 would be a valid alternative here (as they are a trusted JDK distributor, see https://stackoverflow.com/questions/61335109/what-is-the-difference-between-azul-openjdk-zulu-openjdk-and-openjdk).  However, I *believe* Azul's free version of JDK 1.7 ended support in July 2022, according to https://www.azul.com/products/azul-support-roadmap/.   There's a **paid support** option to extend that support until December 2027.

So, you could use their free [JDK 7 LTS version](https://www.azul.com/downloads/?version=java-7-lts&package=jdk) released from July 19, 2022. But, I don't believe they will be releasing any more updates to that unless you switch to their paid support.

**Comment by OyvindLGjesdal** [comment]
Thanks for the info @tdonohue, I didn't see the roadmap/dating on the table on the landing page of azul.

**Comment by tdonohue** [comment]
For any following this ticket, @OyvindLGjesdal has done some good work in trying to get Handle Server v9.3 running with DSpace 6 in #8574.   More eyes on that PR are welcome though, as it's unclear whether the fix results in side effects at this time.

In the meantime, the best solutions remain either downgrading JDK 8, or using the modified version of [Handle Server JAR listed above](https://github.com/DSpace/DSpace/issues/8557#issuecomment-1314382598).

**Comment by mwoodiupui** [comment]
Where does one find the Handle 6.2 sources?

**Comment by ebalnaves** [comment]
With great difficulty.  They are not listed via handle.net any more.  I downloaded them from the Internet Archive (wayback).

Or use the patched version I loaded at https://release.prosentient.com.au/handle62/handle6.2patched.tar.gz

Building is also a bit tricky from the old archive.

**Comment by misilot** [comment]
@mwoodiupui http://www.handle.net/hs-source/hdl6.2.5_02.tar.gz

I got the link from https://web.archive.org/web/20071213200340/http://www.handle.net/download.html

**Comment by mahnkong** [comment]
A working Workaround without the need of changing the handle-server code is to use [Byteman](https://byteman.jboss.org/) ([Documentation](https://downloads.jboss.org/byteman/4.0.20/byteman-programmers-guide.html)) in order to prevent the UOE to be thrown by simply exiting java.lang.Runtime.runFinalizersOnExit on entry. This way, newest JRE8 versions can be used.

Byteman Rule:
```
  RULE runtime.runFinalizersOnExit_disabled
  CLASS java.lang.Runtime
  METHOD runFinalizersOnExit
  AT ENTRY
  IF TRUE
  DO traceln("*** disabled java.lang.Runtime.runFinalizersOnExit ***");
  return
  ENDRULE
```

Example how to set the  JAVA_OPTS environment varuable in order to load above rule during startup (assuming byteman located under _/opt/byteman_ and rule file path is _/opt/byteman/byteman.btm_:
```
JAVA_OPTS="-Dorg.jboss.byteman.transform.all -javaagent:/opt/byteman/lib/byteman.jar=script:/opt/byteman/byteman.btm,boot:/opt/byteman/lib/byteman.jar"

**Comment by ilittle-cnri** [comment]
I've published an updated version of Handle 6.2 with the needed changes. You can get it from https://www.handle.net/hs-source/hdl6.2.5_03.tar.gz. Let me know if the included jar has any issues for folks, or if it resolves this issue.

@tdonohue Since older versions of DSpace are getting Handle from the DSpace Maven repository, are y'all okay publishing this updated version there for your usage?

**Comment by tdonohue** [comment]
@ilittle-cnri : Thanks!  Once someone has had a chance to test the updated JAR from CNRI,  we can then look at pushing it up to the DSpace Maven repository.  I don't think that should be a major issue overall.

**Comment by misilot** [comment]
@tdonohue what would be the best way to test this jar file?

**Comment by tdonohue** [comment]
@misilot & all : Primarily, I'm looking for others to provide feedback as to whether this JAR solves the issues for them or not.  I have to admit, I had forgotten about this ticket and am now in the midst of the final stages of the 7.6 release.  

So, I'd need volunteers to step forward and try out this JAR (download it, install it, see if it works).  If it works, we could then push it up to Maven Central and/or provide instructions for how others can install this if they are similarly impacted.

**Comment by seanaery** [comment]
At Duke, we have successfully used the JAR file @ilittle-cnri posted at https://www.handle.net/hs-source/hdl6.2.5_03.tar.gz in place of the current `handle-6.2.jar` in [our DSpace 6.4 application](https://dukespace.lib.duke.edu/). It is working great for existing and newly-minted handles alike. Many thanks to all for identifying and providing a community solution.

**Comment by tdonohue** [comment]
Thanks all for the verification!  I'll see if I can find time to push this JAR out to Maven Central in the next week or so to make it easier to deploy for impacted sites.  Will post back here when completed.

**Comment by tdonohue** [comment]
All,

It took me longer to get to this than expected... but I just released this patched 6.2.5_03 JAR to Maven Central.   As it was **just released** it may take an hour or two to appear at https://mvnrepository.com/artifact/org.dspace/handle

Once version `6.2.5_03` appears in that list, can someone give it a try to verify it is working?

To test it, simply change this version tag in your Parent/Root POM (`[src]/pom.xml`) to use version `6.2.5_03`:
```
<dependency>
    <groupId>org.dspace</groupId>
    <artifactId>handle</artifactId>
    <version>6.2.5_03</version>
   <!-- Previously this tag will be <version>6.2</version> in both DSpace 5.x and 6.x -->
</dependency>
```

* In 6.x, this dependency tag is here: https://github.com/DSpace/DSpace/blob/dspace-6_x/pom.xml#L1100-L1104
* In 5.x, this dependency tag is here: https://github.com/DSpace/DSpace/blob/dspace-5_x/pom.xml#L1038-L1042

**Comment by seanaery** [comment]
Thank you @tdonohue . It is working for us, e.g. with https://gitlab.oit.duke.edu/ddr/dspace/-/blob/dukespace-6_prod/pom.xml?ref_type=heads#L1100-1104 we can see https://hdl.handle.net/10161/22434 resolving correctly.

**Comment by OyvindLGjesdal** [comment]
Thanks @tdonohue and everyone for testing it out. I've updated the dependency now and all looks good. This was for dspace5 (clarin-dspace fork) fork. Should I just close the issue, or should the pom.xml be updated for the 5x and 6x branches first?

**Comment by alanorth** [comment]
@OyvindLGjesdal I've updated our repository as well, verified working with latest JDK 1.8.

Regarding this issue, I think it can be closed. DSpace 6.x goes out of support in a few days (on 2023-07-01) and this simple fix is working and documented here, so in my opinion there is no need to create a pull request.

**Comment by tdonohue** [comment]
Thanks for the verification all!  I agree with @alanorth that this will not be possible to package up into a new 5.x or 6.x release.  5.x is EOL already, and 6.x goes EOL in 2 days.

However, for any sites impacted, the fix is extremely easy to apply locally (especially thanks to PR "templates" created by @misilot !)

**PATCH INSTRUCTIONS**
1. Apply the minor changes to your Parent POM (`[src]/pom.xml`)
    * For 5.x, apply changes shown in this PR: https://github.com/DSpace/DSpace/pull/8929/.   
        * Here's a downloadable Patch file equivalent: https://github.com/DSpace/DSpace/pull/8929.patch
    * For 6.x, apply changes shown in this PR: https://github.com/DSpace/DSpace/pull/8930
        * Here's a downloadable Patch file equivalent: https://github.com/DSpace/DSpace/pull/8930.patch
2. Rebuild/redeploy your DSpace per 5.x or 6.x Upgrade Instructions.  For example:
    * `mvn -U clean package`
    * `ant update`
    * (If necessary, copy final WARs into Tomcat)
3. Restart Tomcat (i.e. your servlet container)

Closing this ticket as "fixed".  Apply the patch per above instructions if you are impacted.

**Comment by monokini3d** [comment]
Hi. May be somebody will patch dspache handle 6.2.5 one more time? We found wrong headers in it.

https://github.com/louislam/uptime-kuma/issues/5912

> Developers from handle.net told me this:
> 
> When I do a hex dump from the version of the handle server you are running I do see that it is using inconsistent line break styles, which violates the HTTP specification.
>  
```
> ***$ curl -i http://yoursite:8000/ | hexdump -C | head -100
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2794    0  2794    0     0   8439      0 --:--:-- --:--:-- --:--:--  8441
> 00000000  48 54 54 50 2f 31 2e 30  20 32 30 30 20 4f 4b 0a  |HTTP/1.0 200 OK.|
> 00000010  43 6f 6e 74 65 6e 74 2d  74 79 70 65 3a 20 74 65  |Content-type: te|
```
> 
>  e.g. That first line ends with hex 0a which is LF only.
> 
> However if I do the same hex dump from a handle server running the current version of the software 9.3.1 the line break styles are consistent and correct in compliance with HTTP 1.1
```
> ***$ curl -i http://localhost:8000/ | hexdump -C | head -20
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2329  100  2329    0     0  1341k      0 --:--:-- --:--:-- --:--:-- 2274k
> 00000000  48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d  |HTTP/1.1 200 OK.|
> 00000010  0a 44 61 74 65 3a 20 4d  6f 6e 2c 20 31 36 20 4a  |.Date: Mon, 16 J|
```
> 
> Here we see the first line is terminated with 0d 0a, which is CRLF.

**Comment by tdonohue** [comment]
@monokini3d : Sorry, but DSpace 5 and 6 are both end-of-life. No additional patching of Handle 6.2.5 will occur because that version was only used in DSpace 5 and 6 (and earlier).  

So, we will not provide any more patching support for Handle 6.x, as we now use Handle 9.x (which is built/maintained by `net.handle`: https://mvnrepository.com/artifact/net.handle/handle)
