### ISSUE TITLE
Dspace 5.11 and 6.4 error uploading via JSPUI on Windows

### ISSUE THREAD

**Issue by monokini3d** [DSpace/DSpace#8609]
It is impossible to upload a files via web interface because of hardcoded paths...

For example - java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:/dspace/upload)

```
2022-12-12 21:54:08,656 ERROR org.dspace.app.webui.util.FileUploadRequest @ Error processing resumable upload chunk: temporary chunk file would be created outside permissible temp dir (c:/dspace/upload) for file: nito_2022_2_001.pdf
2022-12-12 21:54:08,656 WARN  org.dspace.app.webui.servlet.InternalErrorServlet @ :session_id=D73871843206AD4BF1898E9760805C91:internal_error:-- URL Was: http://test.ideafix.co/tools/edit-item
-- Method: POST
-- Parameters were:

java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:/dspace/upload)
	at org.dspace.app.webui.util.FileUploadRequest.<init>(FileUploadRequest.java:171)
	at org.dspace.app.webui.servlet.admin.EditItemServlet.processUploadBitstream(EditItemServlet.java:940)
	at org.dspace.app.webui.servlet.admin.EditItemServlet.doDSPost(EditItemServlet.java:175)
	at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:115)
	at org.dspace.app.webui.servlet.DSpaceServlet.doPost(DSpaceServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.app.webui.filter.RegisteredOnlyFilter.doFilter(RegisteredOnlyFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:689)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:/dspace/upload)
	at org.dspace.app.webui.util.FileUploadRequest.<init>(FileUploadRequest.java:142)
	... 33 more

```

**Comment by tdonohue** [comment]
@monokini3d : Took a quick look at this.

Could you try simply updating the `upload.temp.dir` setting in your "dspace.cfg" or "local.cfg" to use Windows backslashes?
```
# NOTE: you have to use double backslashes for each slash, as backslash is a special character
upload.temp.dir = C:\\dspace\\upload
```

It appears that a security fix in 5.11/6.4 may now require that this `upload.temp.dir` setting has operating-system appropriate slashes.  This means that Unix/Linux would require it to use forward slashes `/`, while Windows would require it to use backward slashes `\`.

**Comment by monokini3d** [comment]
May be I will get same error with reports, sitemaps, csv metadata and saf/zip files... I think, It is enough complex case. Isnt it?

**Comment by monokini3d** [comment]
feedback:

config:
```
# Where to temporarily store uploaded files
upload.temp.dir = c:\\dspace\\upload

```


log

```
2022-12-12 22:35:18,250 ERROR org.dspace.app.webui.util.FileUploadRequest @ Error processing resumable upload chunk: temporary chunk file would be created outside permissible temp dir (c:\dspace\upload) for file: nito_2022_2_001.pdf
2022-12-12 22:35:18,250 WARN  org.dspace.app.webui.servlet.InternalErrorServlet @ :session_id=86698A7DEB74E35723AAA88FD49000BF:internal_error:-- URL Was: http://test.ideafix.co/tools/edit-item
-- Method: POST
-- Parameters were:

java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:\dspace\upload)
	at org.dspace.app.webui.util.FileUploadRequest.<init>(FileUploadRequest.java:171)
	at org.dspace.app.webui.servlet.admin.EditItemServlet.processUploadBitstream(EditItemServlet.java:940)
	at org.dspace.app.webui.servlet.admin.EditItemServlet.doDSPost(EditItemServlet.java:175)
	at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:115)
	at org.dspace.app.webui.servlet.DSpaceServlet.doPost(DSpaceServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.app.webui.filter.RegisteredOnlyFilter.doFilter(RegisteredOnlyFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:689)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:\dspace\upload)
	at org.dspace.app.webui.util.FileUploadRequest.<init>(FileUploadRequest.java:142)
	... 33 more

```

**Comment by monokini3d** [comment]
I also tried this - upload.temp.dir = c:\\dspace\\upload\\

and got htis - java.io.IOException: Error processing resumable chunk directory c:\dspace\upload\nito_2022_2_001.pdf (filename: nito_2022_2_001.pdf). Temporary upload directory would be created outside permissible base temp dir (c:\dspace\upload\)

**Comment by tdonohue** [comment]
@monokini3d : Thanks for trying.  This error is very confusing to me, as obviously `c:\dspace\upload\nito_2022_2_001.pdf` is in the directory `c:\dspace\upload`... even though the error claims it is not.   The error is being thrown in this area of the code: https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-jspui/src/main/java/org/dspace/app/webui/util/FileUploadRequest.java#L139-L145   The code there looks **correct** at a glance, so it's surprising that this isn't working on Windows.

I suspect this will take some digging, so I'll see if I can locate a volunteer to help dig into this.   The code linked to above is all brand new code in 5.11 / 6.4, but it's necessary to avoid [this vulnerability in the JSPUI](https://github.com/DSpace/DSpace/security/advisories/GHSA-qp5m-c3m9-8q2p).  That also does mean this particular bug ticket would only affect the JSPUI on Windows. Unfortunately, it's not obvious to me why this code isn't working on Windows.

**Comment by monokini3d** [comment]
@tdonohue 
I spend a lot of time to find a mistake on catalina side (catalina.policy), but it is our own mistake :)

**Comment by tdonohue** [comment]
@monokini3d : Are you saying you have already found a fix for this bug ticket on your side?  I'm confused about your last message.  Could you clarify what you mean by "it is our own mistake"?

**Comment by monokini3d** [comment]
No, only locate... sorry, english is not my own.

**Comment by monokini3d** [comment]
https://github.com/DSpace/DSpace/commit/d1dd7d23329ef055069759df15cfa200c8e3.patch

The problem is here. I checked 5.11 code without this pach and it is working fine. I can not make a woirking code with "JPSUI resumable upload dir validation", but I can fix it on my instance with old code witjout a patch. I think, it is an overengineering to make such validations. It is possible to validate via catalina.policy. I use built in policy tools in linux distributions to allow tomcat to wtite in /dspace/upload or /dspace/var, and now we have two validators to write in /dspace/upload in linux - on OS side and on service side.

**Comment by mwoodiupui** [comment]
From slack:
The only thing I can think of is that getCanonicalPath may not be returning what you expect.  You might need to canonicalize both paths.  Also Path.startsWith() might be better for paths than String.startsWith().  Windows filesystem paths include weird things that we usually don't see.

**Comment by tdonohue** [comment]
@monokini3d : This ticket was closed automatically as [5.x and 6.x are both end of life](https://wiki.lyrasis.org/display/DSPACE/Support+for+DSpace+5+and+6+is+ending+in+2023).  Apologies for the confusion.
