### ISSUE TITLE
Error creating item in dspace-cris-2022.02.00

### ISSUE THREAD

**Issue by luisbiblio77** [DSpace/DSpace#8638]
Dear friends, I have the following problem sending items in Dspace Cris 2022.02.00 I will appreciate your help if possible please.

Characteristics
Dspace Chris 2022.02.00 | Ubuntu server 20.04 | postgresql 12 | tomcat 9

After creating a collection, be it Person, OrgUnit, Journal or any other value, the items are sent. In the graphic part, the message you get is: "There was a problem sending the article. Please try again later."

Checking the logs in /dspace/log/ I get the following:

2023-01-17 23:34:11,300 ERROR ef58dbeb-3f67-4cd3-b760-6197a8fbf95a 4698d980-dfcd-4b15-b2f7-dc0fcf4e2cbf org.dspace.app.rest.converter.AInprogressItemConverter @ An error occurred during the unmarshal of the data for the section correction - reported error: Relationship type isCorrectionOfItem does not exist
java.lang.IllegalArgumentException: Relationship type isCorrectionOfItem does not exist
        at org.dspace.versioning.ItemCorrectionService.lambda$findRelationshipType$1(ItemCorrectionService.java:177) ~[dspace-api-cris-2022.02.00.jar:cris-2022.02.00]
        at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]

8dbeb-3f67-4cd3-b760-6197a8fbf95a 26c0ec2e-611c-4def-858f-971d5ee8e1c3 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Relationship type isCorrectionOfItem does not exist at: org.dspace.versioning.ItemCorrectionService.lambda$findRelationshipType$1(ItemCorrectionService.java:177))

2023-01-17 23:46:20,446 INFO  ef58dbeb-3f67-4cd3-b760-6197a8fbf95a 45c807f1-2458-4a67-8757-0c1735250a7e org.dspace.usage.LoggerUsageEventListener @ luis@bibliolatino.com::workflow_item:item_id=470ba0a5-4971-4bb0-b33f-4d5371d6bdaa
2023-01-17 23:46:20,456 WARN  ef58dbeb-3f67-4cd3-b760-6197a8fbf95a 45c807f1-2458-4a67-8757-0c1735250a7e org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Relationship type isCorrectionOfItem does not exist at: org.dspace.versioning.ItemCorrectionService.lambda$findRelationshipType$1(ItemCorrectionService.java:177))

2023-01-17 23:46:20,456 WARN  ef58dbeb-3f67-4cd3-b760-6197a8fbf95a 45c807f1-2458-4a67-8757-0c1735250a7e org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Relationship type isCorrectionOfItem does not exist at: org.dspace.versioning.ItemCorrectionService.lambda$findRelationshipType$1(ItemCorrectionService.java:177))

According to the documentation the following scripts were run

sudo /dspace/bin/dspace dsrun org.dspace.app.util.InitializeEntityTypesOnly -d
sudo /dspace/bin/dspace dsrun org.dspace.app.util.InitializeEntities -f correction-relationship-types.xml

No results for sending items in dspace cris

**Comment by tdonohue** [comment]
Closing as DSpace-CRIS is a separate application from DSpace, and this ticketing system is for DSpace tickets only.

For DSpace-CRIS support, you need to contact 4Science (the organization who builds/maintains DSpace-CRIS), or use one of their support options detailed at https://wiki.lyrasis.org/display/DSPACECRIS
