### ISSUE TITLE
Sword 1 submission fails for users without WRITE permission

### ISSUE THREAD

**Issue by olli-gold** [DSpace/DSpace#8647]
**Describe the bug**
The submission of an item via Sword version 1 fails, if a user does the submission, is not an administrative user. The error message in the backend is `org.dspace.authorize.AuthorizeException: Authorization denied for action WRITE on ITEM:4f4abebf-287f-481d-9be8-b288d331be2d by user 8c8c9dea-4a88-47ef-b882-9931f53aca90`. When I use a user with Admin permissions, the submission is successfull (so I guess it cannot be a matter of my test command or the test item).

**To Reproduce**
1. Submit an item via Sword version 1 to a collection, where the user is supposed to be able to add items.

Used command for submission: `curl -k -i --data-binary "@file.zip" -H "Content-Disposition:filename=file.zip" -H "Content-Type:application/zip" -H "X-Packaging:http://purl.org/net/sword-types/METSDSpaceSIP" -u [user]:[password] https://<dspace-backend-url>/server/sword/deposit/<collection-handle>`. If the user I set a user with just submission permission to the collection at `collection-handle`, the submission fails. If it's an admin, it works.

**Expected behavior**
If the user is allowed to add new items to the collection they submit to via SWORD, this should work (as well as it works for a manual submission).

**Related work**
In fact I had filed a bug report for DSpace 6 many years ago, which is describing the same problem (and which apparently was never resolved, although the old ticket was closed): https://github.com/DSpace/DSpace/issues/7114

**Comment by tdonohue** [comment]
@olli-gold : Had a chance to test this on my end.  I've verified the same behavior.

* SWORD v1 deposit works for a user with full Administrator privileges
* SWORD v1 deposit works for a user with *Collection* Administrator privileges
* SWORD v1 deposit does NOT work for a user with *only* Submit privileges on the Collection.  I get a 500 response as well, and the error in the logs is this:
```
2023-03-08 20:45:36,511 ERROR unknown e7b21054-0832-4220-9e7d-41d895bf5456 org.dspace.sword.DSpaceSWORDServer @ caught exception:
org.dspace.sword.DSpaceSWORDException: org.dspace.authorize.AuthorizeException: Authorization denied for action WRITE on ITEM:a552708a-fd39-4dc0-a80f-92f6d1ea585f by user 914955b1-cf2e-4884-8af7-a166aa24cf73
        at org.dspace.sword.SWORDMETSIngester.ingest(SWORDMETSIngester.java:173) ~[dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.sword.CollectionDepositor.doDeposit(CollectionDepositor.java:138) ~[dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.sword.DepositManager.deposit(DepositManager.java:166) ~[dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.sword.DSpaceSWORDServer.doDeposit(DSpaceSWORDServer.java:120) [dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.purl.sword.server.DepositServlet.doPost(DepositServlet.java:323) [dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
...
Caused by: org.dspace.authorize.AuthorizeException: Authorization denied for action WRITE on ITEM:a552708a-fd39-4dc0-a80f-92f6d1ea585f by user 914955b1-cf2e-4884-8af7-a166aa24cf73
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:171) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:119) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.authorize.AuthorizeServiceImpl.authorizeAction(AuthorizeServiceImpl.java:113) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.update(ItemServiceImpl.java:579) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.update(ItemServiceImpl.java:92) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.packager.PackageUtils.updateDSpaceObject(PackageUtils.java:583) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.packager.AbstractMETSIngester.ingestObject(AbstractMETSIngester.java:531) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.packager.AbstractMETSIngester.ingest(AbstractMETSIngester.java:250) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.sword.SWORDMETSIngester.ingest(SWORDMETSIngester.java:108) ~[dspace-sword-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
```

So, this is definitely a bug in SWORDv1.  For the time being, it could be worked around by using a Collection Admin or similar.

I'll flag this as help wanted, as I think we'd need to find a volunteer to help with this one.
