### ISSUE TITLE
Errors in demo OAI

### ISSUE THREAD

**Issue by dagrenzer** [DSpace/DSpace#8739]
**Describe the bug**
The OAI endpoint for the demo server returns errors for most requests. These are either internal server 500 errors, or simply blank/incomplete XML responses, depending on the request. I can't tell if it is a misconfiguration specific to the demo server or if it is something in the code.

**To Reproduce**
1. Visit [https://api7.dspace.org/server/oai/request?verb=ListMetadataFormats](https://api7.dspace.org/server/oai/request?verb=ListMetadataFormats) , you will get an empty XML response. The same goes for ListIdentifiers and ListSets.
2. Other requests, for specific records, such as [https://api7.dspace.org/server/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:demo7.dspace.org:10673/4515](https://api7.dspace.org/server/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:demo7.dspace.org:10673/4515), or for other contexts return either internal server 500 errors or empty XML. 

**Expected behavior**
[https://api7.dspace.org/server/oai/](https://api7.dspace.org/server/oai/) and [https://api7.dspace.org/server/oai/request?verb=ListRecords&metadataPrefix=oai_dc](https://api7.dspace.org/server/oai/request?verb=ListRecords&metadataPrefix=oai_dc) still return the expected, normal responses.

**Related work**
I don't see an existing issue about this.

**Comment by abdullah-abunada** [comment]
Hello everybody,

I faced the same issue (internal server error 500) when accessing the records page.
for example: `request?verb=ListRecords&metadataPrefix=oai_dc&set=com_123456789_2`
our dspace instance link: 
[https://api.dspace.up.edu.ps/server/oai/request?verb=ListRecords&metadataPrefix=oai_dc&set=com_123456789_2](url)
` SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet [dispatcherServlet] threw exception
	java.lang.IllegalStateException: getOutputStream() has already been called for this response
		at org.apache.catalina.connector.Response.getWriter(Response.java:584)
		at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:227)
		at org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration$StaticView.render(ErrorMvcAutoConfiguration.java:227)
		at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373)
		at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
		at org.springframework.boot.web.servlet.support.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:160)
		at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
		at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
		at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by abdullah-abunada** [comment]
Hello,

I solved this issue, the missioned issue caused on Arabic or other languages that need the UTF-8 encoding.
By default tomcat server did not create the new xml files using UTF-8 encoding, so we need enforce it  to use UTF-8 encoding when it create new file by setting this configuration via cli or from GUI then restart the server.

` JAVA_OPTS="-Dfile.encoding=UTF-8"`

Best Regard
