### ISSUE TITLE
doi-organiser command line NPE when using VersionedDOIIdentifierProvider

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#8750]
**Describe the bug**
An NPE is thrown when trying to reserve (--reserve-doi) or register (--register-doi) an individul DOI for an item

```
/home/dspace/dspace/bin/dspace doi-organiser --reserve-doi 1810/347187
Exception: null
java.lang.NullPointerException
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:502)
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:492)
	at org.dspace.identifier.doi.DOIOrganiser.runCLI(DOIOrganiser.java:310)
	at org.dspace.identifier.doi.DOIOrganiser.main(DOIOrganiser.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```

**To Reproduce**
1. Enable VersionedDOIIdentifierProvider in identifier-service.xml
2. Run command doi-organiser with --reserve-doi or --register-doi option

**Expected behavior**
The DOI is reserved or registered successfully

**Related work**
Link to any related tickets or PRs here.

**Comment by amgciadev** [comment]
There are two lines of code in the mint method in https://github.com/DSpace/DSpace/blob/bdb88724ac8434956ec52dcdcb182f2d13e5edd5/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java

https://github.com/DSpace/DSpace/blob/bdb88724ac8434956ec52dcdcb182f2d13e5edd5/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java#L129 and https://github.com/DSpace/DSpace/blob/bdb88724ac8434956ec52dcdcb182f2d13e5edd5/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java#L148

where the DOI.SCHEME is not appended when returning the DOI. This is causing for this call in DOIOrganiser to send a DOI that does not exist: https://github.com/DSpace/DSpace/blob/bdb88724ac8434956ec52dcdcb182f2d13e5edd5/dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java#L728
