### ISSUE TITLE
.../config/log4j2.xml (Permission denied)

### ISSUE THREAD

**Issue by smahi** [DSpace/DSpace#8782]
**Describe the bug**
I installed dspace 7.5 without errors, but testing the backend using `ip-addr:8080/server` I got `404 not found` error
But i found this error message in the tomcat9 log file

`$ cat /var/log/tomcat9/catalina.2023-04-16.log`

```
Caused by: java.lang.IllegalStateException: Could not initialize Log4J2 logging from /home/dspace/dspace/config/log4j2.xml
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.loadConfiguration(Log4J2LoggingSystem.java:230)
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.loadConfiguration(Log4J2LoggingSystem.java:193)
                at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
                at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.initialize(Log4J2LoggingSystem.java:169)
                at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:316)
                ... 59 more
        Caused by: java.io.FileNotFoundException: /home/dspace/dspace/config/log4j2.xml (Permission denied)
                at java.base/java.io.FileInputStream.open0(Native Method)
                at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
                at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
                at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
                at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
                at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
                at java.base/java.net.URL.openStream(URL.java:1165)
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.getConfigurationSource(Log4J2LoggingSystem.java:241)
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.load(Log4J2LoggingSystem.java:236)
                at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.loadConfiguration(Log4J2LoggingSystem.java:221)
                ... 64 more
16-Apr-2023 10:42:32.532 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat9/webapps/server] has finished in [23,695] ms
16-Apr-2023 10:42:32.541 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
16-Apr-2023 10:42:32.564 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [25948] milliseconds
                                                                                                                            
```

As you can see there is permission issue on `/home/dspace/dspace/config/log4j2.xml`
the file does exist and even when gave the whole directory a permissions of `777` and restart tomcat9 i get the same error.
please help

**Comment by tdonohue** [comment]
@smahi : Tech support questions / requests for help should be asked via one of our Support options available at https://wiki.lyrasis.org/display/DSPACE/Support  I'd recommend asking this via the dspace-tech mailing for more attention: https://groups.google.com/g/dspace-tech

This doesn't sound like a bug in DSpace itself, so I'm closing the ticket.  It sounds like a permissions issue on either the file itself, or your entire `/home/dspace` directory or similar.

**Comment by bardayilmaz** [comment]
I am also having this problem on Ubuntu 22.04/Debian 12 machines but not having on Ubuntu 20.04/Debian 11. Did you solve it?
