### ISSUE TITLE
Frecuently appers Internal read or write operation failed - with Error 500 Broken PIPE

### ISSUE THREAD

**Issue by edwinsaavedra99** [DSpace/DSpace#8858]
We deployed a dspace 7.5 production application, however, when reviewing the application logs, this error frequently appears:

I don't have specific replay steps as the error occurs a few minutes after launching the app and then it crashes after a while anyway. In the log file we also have a lot of requests per second. We think it may be due to spiders.

[dspace.log](https://github.com/DSpace/DSpace/files/11527145/dspace.log)

```
2023-05-21 23:09:45,799 ERROR unknown 6ab2c4cb-7c27-4165-9de1-3c56bd84d92c org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An internal read or write operation failed (status:500)
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:371) ~[catalina.jar:8.5.86]
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:846) ~[catalina.jar:8.5.86]
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:751) ~[catalina.jar:8.5.86]
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:406) ~[catalina.jar:8.5.86]
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:384) ~[catalina.jar:8.5.86]
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96) ~[catalina.jar:8.5.86]
	at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.write(OnCommittedResponseWrapper.java:638) ~[spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.util.StreamUtils.copyRange(StreamUtils.java:204) ~[spring-core-5.3.20.jar:5.3.20]
	at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeResourceRegion(ResourceRegionHttpMessageConverter.java:161) ~[spring-web-5.3.20.jar:5.3.20]
	at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeInternal(ResourceRegionHttpMessageConverter.java:136) ~[spring-web-5.3.20.jar:5.3.20]
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104) ~[spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.20.jar:5.3.20]
	at org.springframework.hateoas.server.mvc.RepresentationModelProcessorHandlerMethodReturnValueHandler.handleReturnValue(RepresentationModelProcessorHandlerMethodReturnValueHandler.java:108) ~[spring-hateoas-1.4.2.jar:1.4.2]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:488) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:582) [servlet-api.jar:?]
```

**Comment by tdonohue** [comment]
@edwinsaavedra99 : I'd recommend looking for other errors in the DSpace or Tomcat logs.  A "Broken Pipe" error tends to be a very generic error that says there's issues with clients connecting to your backend application (e.g. network issues, very slow performance, or users are canceling a download before the response is completed).  

This sort of error might be harmless if it occurs infrequently.  But if it occurs frequently, it could be an indication of something more severe (but the only way to tell is to look for other errors in the logs).  Here's our troubleshooting guide to find errors: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

Based on the logs you shared above, it appears to me that there might be an issue download files from your site.  Immediately *after* those errors occur, you seem to always have an error like this:
```
2023-05-21 23:13:12,046 ERROR unknown unknown org.springframework.boot.web.servlet.support.ErrorPageFilter @ Cannot forward to error page for request [/api/core/bitstreams/5368afc9-e9f0-467b-9f99-7106f9044aaa/content] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
```

Notice that the "request" listed there is a Bitstream download.  This `/api/core/bitstreams/[uuid]/content` endpoint is used by the REST API to download Bitstreams.  It may be possible that whoever is downloading the bitstream is either cancelling the download (which could cause the error) or the download may be timing out in some way.

Overall, we don't have enough information to help in this scenario.  I'm also not able to reproduce this and have not heard of others who've experienced it.  Therefore, my best guess is this may be a configuration or performance issue specific to your setup. Nonetheless, we can leave this ticket open for a bit to see if anyone else experiences something similar.
