### ISSUE TITLE
CrossRef external import integration breaks if you change the DOI field

### ISSUE THREAD

**Issue by alanorth** [DSpace/DSpace#8865]
**Describe the bug**
In DSpace 7.6-SNAPSHOT, the CrossRef external import integration breaks if you change the DOI field mapping. The error in the DSpace log is:

```console
2023-05-24 09:18:20,420 ERROR e8bb77ea-6cf1-4543-a0e7-cbde0e03d609 51a07ef3-a8cb-4e80-8fc8-38aa6b679228 org.dspace.importer.external.service.components.AbstractRemoteMetadataSource @ Source exception Illegal character in path at index 31: https://api.crossref.org/works/{entryId}
java.net.URISyntaxException: Illegal character in path at index 31: https://api.crossref.org/works/{entryId}
        at java.net.URI$Parser.fail(URI.java:2976) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3147) ~[?:?]
        at java.net.URI$Parser.parseHierarchical(URI.java:3229) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3177) ~[?:?]
        at java.net.URI.<init>(URI.java:623) ~[?:?]
        at org.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:82) ~[httpclient-4.5.13.jar:4.5.13]
        at org.dspace.importer.external.crossref.CrossRefImportMetadataSourceServiceImpl$SearchByIdCallable.call(CrossRefImportMetadataSourceServiceImpl.java:194) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.importer.external.crossref.CrossRefImportMetadataSourceServiceImpl$SearchByIdCallable.call(CrossRefImportMetadataSourceServiceImpl.java:178) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
<snip incredibly long trace>
```

**To Reproduce**
1. Change the `crossref.id` bean's metadata field mapping from `dc.identifier.doi` to something else (we use `cg.identifier.doi`):

```diff
diff --git a/dspace/config/spring/api/crossref-integration.xml b/dspace/config/spring/api/crossref-integration.xml
index e01b613833..0a3c292808 100644
--- a/dspace/config/spring/api/crossref-integration.xml
+++ b/dspace/config/spring/api/crossref-integration.xml
@@ -37,7 +37,7 @@
         <property name="query" value="/DOI"/>
     </bean>
     <bean id="crossref.id" class="org.dspace.importer.external.metadatamapping.MetadataFieldConfig">
-        <constructor-arg value="dc.identifier.doi"/>
+        <constructor-arg value="cg.identifier.doi"/>
     </bean>
 
     <bean id="crossrefJournalContrib" class="org.dspace.importer.external.metadatamapping.contributor.SimpleJsonPathMetadataContributor">
```

2. Start an external import from MyDSpace → External import button → CrossRef with any DOI, for example: 10.1186/s40781-015-0073-1

<p align=center>
  <img src="https://github.com/DSpace/DSpace/assets/191754/5307f360-f4a2-4e84-95f7-434d83c35ea2" width=600 />
</p>

The preview is shown, with any fields that have matched. You can see from the i18n keys in the UI that we have changed several other fields in addition the DOI, but at this stage they are all matched.

3. Click start submission and the UI hangs.

<p align=center>
  <img src="https://github.com/DSpace/DSpace/assets/191754/477ab4c7-c9f1-4b4c-9aa1-6271af7c5e10" width=600 />
</p>

Error is printed in the log.

**Expected behavior**
The import should use the DOI field that is mapped in the configuration.

**Comment by alanorth** [comment]
I found the cause of this. It's not a bug, but a misconfiguration. In our case we use a different metadata field for the DOI, and we need to change it in two places for Crossref integration:

- `dspace/config/spring/api/crossref-integration.xml`
- `dspace/config/spring/api/external-services.xml`
