### ISSUE TITLE
Deleting an In Progress Submission logs a seemingly harmless Hibernate ObjectNotFoundException

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8883]
**Describe the bug**
First discovered while testing #8856, but I've since discovered this problem also occurs on `main` (pre-7.6). 

If you watch the `dspace.log` while deleting an in-progress submission, you will see a large number of logged Hibernate stacktraces which seem to originate from the `IndexEventConsumer`.  The Hibernate stacktraces appear as `INFO` messages and they always reference the deleted Item.  The same stacktrace will appear several times in the log, immediately after the (usual) WARN messages for Bitstreams and Bundles.  

Here's an example.
```
2023-06-02 19:15:41,649 WARN  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 66b3a51f-3fa1-4d8f-9bfa-c7c0d27af3b8 org.dspace.discovery.IndexEventConsumer @ REMOVE event, could not get object for BUNDLE id=d2b33dbc-5ef8-49c7-9d2f-0c041cc046b1, perhaps it has been deleted.
2023-06-02 19:15:41,649 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 66b3a51f-3fa1-4d8f-9bfa-c7c0d27af3b8 org.hibernate.event.internal.DefaultLoadEventListener @ HHH000327: Error performing load command
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [org.dspace.content.Item#e2fe939d-b9ad-4818-a190-2392c233e2d3]
        at org.hibernate.boot.internal.StandardEntityNotFoundDelegate.handleEntityNotFound(StandardEntityNotFoundDelegate.java:28) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.returnNarrowedProxy(DefaultLoadEventListener.java:374) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:317) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1220) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:202) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2848) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2825) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2781) [hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2825) [hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1019) [hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at jdk.internal.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:351) [hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at com.sun.proxy.$Proxy388.get(Unknown Source) [?:?]
        at org.dspace.core.AbstractHibernateDAO.findByID(AbstractHibernateDAO.java:94) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.find(ItemServiceImpl.java:206) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.find(ItemServiceImpl.java:91) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.event.Event.getSubject(Event.java:392) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.discovery.IndexEventConsumer.consume(IndexEventConsumer.java:83) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.event.BasicDispatcher.dispatch(BasicDispatcher.java:104) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.core.Context.dispatchEvents(Context.java:466) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.core.Context.commit(Context.java:435) [dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.deleteById(DSpaceRestRepository.java:206) [classes/:7.6-SNAPSHOT]
```

The cause of these errors is unclear to me.  But, they seem harmless (but annoying, as they take up many lines of the log file after the deletion). The in-progress Submission is still deleted successfully.

**To Reproduce**
1. Watch the `dspace.log` on the backend while performing the following...
2. Login as a user with submit permissions.
3. Start a new submission.
4. Make some edits, click "Save for Later"
5. From MyDSpace, click Delete for that new submission.  You'll see exceptions similar to the above in your dspace.log

These exceptions do NOT seem to appear for deletions of archived Items.  So far, I've only been able to reproduce this for Items which are still in-progress submissions.

**Expected behavior**
No Hibernate stacktrace should be logged.

**Comment by tdonohue** [comment]
Ran into this today... this issue also impacts pre-8.0

**Comment by abollini** [comment]
I have spent some time on that today for a DSpace 7.6.1-based project; the log message is not a real problem but just garbage.

This issue is related to https://hibernate.atlassian.net/browse/HHH-7861
What happen is that our hibernate session contains a reference to a hibernate proxy for the Item in the WorkflowItem that has been deleted. Such proxy, when accessed, of course returns a null concrete object as the Item is gone, and this throws an ObjectNotFound exception that is logged here
https://github.com/hibernate/hibernate-orm/blob/5.6.15/hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java#L116

the exception is catched and ignored later on by the caller 
https://github.com/hibernate/hibernate-orm/blob/5.6.15/hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java#L2852
with this comment "// if session cache contains proxy for non-existing object" but the message was already sent to the log.
In the current hibernate main this issue is solved, the code is changed a bit but the "new corresponding part" is there

 https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java#L401

the change has been introduced with https://github.com/hibernate/hibernate-orm/pull/5351/files#diff-015aeb0f9c1c27e759cd795ce08347c3c726755835fc48cb8b59273cdbbfb407

that is part of hibernate since version 6.2.0... this conflict with what was noted by @tdonohue  on 7 Jun using the pre-8.0 code as I expect that version 6.4+ was in use. We should check the problem again with the latest code

**Comment by tdonohue** [comment]
@abollini : Thanks for the additional notes!

I just tried it again with the latest `main` code (pre-9.0), and the problem still exists, even though we are now using Hibernate`6.4.8.Final`.  It's easily reproducible by following the "To Reproduce" steps listed in the ticket description above.

1. Watch the dspace.log on the backend while performing the following...
2. Login as a user with submit permissions (or admin permissions)
3. Start a new submission.
4. Make some edits, click "Save for Later"
5. From MyDSpace, click Delete for that new submission. You'll see exceptions similar to the above in your dspace.log

I'm not sure why we're still hitting this issue, but it makes me wonder if it's something in our own code that continues to report this misleading logged error.  As stated though, the error in the logs is harmless.  The deletion works fine.
