### ISSUE TITLE
'No _links section found' error is displayed on the dspace demo

### ISSUE THREAD

**Issue by Marwa1988-S** [DSpace/DSpace#8934]
**Describe the bug**
"error.top-level-communities" Error appeared on the home page of the site and the communities list was not brought up.

**To Reproduce**
There is no specific sequence for producing this error. It was while browsing and testing some functions on the dspace UI.

**Expected behavior**
The communities list schould be displayed

![Screenshot from 2023-06-30 11-43-10](https://github.com/DSpace/DSpace/assets/92751337/5b035dd4-0247-4d66-9ad3-d1f0327186b2)

**Comment by tdonohue** [comment]
Demo site seems up now.  I cannot reproduce this.

I suspect the backend was temporarily down or being rebooted at the time this occurred.  This "No _links section found" error tends to mean that the frontend has lost communication with the backend.  See https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-%22No_linkssectionfoundat...%22errorfromUserInterface

**Comment by MW3000** [comment]
I was very happy to see this error plop up on the official demo site. We have a perfectly well running production site, and several test servers, which all work fine. Except one, where we intermittently experience exactly this error. Everything seems configured right, `yarn test:rest` shows everything is alright, yet, we get this error in the browser and on the frontend server log. Otherwise the site works too. It is not all calls to the API that do not work. Also if one calls `http://xxx/server/api/discover`, the `_links` section is there and it contains the search link too. I tried it with both 7.5 and 7.6, it does not make any difference.

So if this error message means anything to anyone I would be happy to hear about it. I leave it here for reference.

```
No _links section found at http://xxx/server/api/discover
No _links section found at http://xxx/server/api/discover
ERROR Error: undefined doesn't contain the link search
    at /srv/dspace-ui-deploy/dist/server/main.js:1:968356
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4446009
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4445996
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4485325
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
ERROR Error: undefined doesn't contain the link search
    at /srv/dspace-ui-deploy/dist/server/main.js:1:968356
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4446009
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4445996
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
    at /srv/dspace-ui-deploy/dist/server/main.js:1:4485325
    at OperatorSubscriber2._this._next (/srv/dspace-ui-deploy/dist/server/main.js:1:4405600)
    at OperatorSubscriber2.Subscriber2.next (/srv/dspace-ui-deploy/dist/server/main.js:1:4356162)
```
