### ISSUE TITLE
grant-deny-request-copy.component.html: Cannot read properties of null (reading 'decisionDate')

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#8973]
## Bug Description

**Preliminary Note:** Unfortunately, I was not able to reproduce this bug on the DSpace demo instance since the email delivery is disabled (I did not receive request-a-copy emails). Perhaps someone who is able to receive request-a-copy emails can try to reproduce this bug?

The request-a-copy email contains a paragraph

> To answer, click https://somedomain.tld/request-a-copy/<token>. Whether you choose to grant or deny the request, we think that it''s in your best interest to respond.

If the author opens the link, he/she is requested to log in. After the successful login, a white page with title _Document copy request_ is shown (you can find a screenshot below). 

![image](https://github.com/DSpace/DSpace/assets/952735/6052bbbf-7a92-4fbb-b9ea-0727d9f83501)

The JS console contains error messages

```
ERROR TypeError: Cannot read properties of null (reading 'decisionDate')
    at GrantDenyRequestCopyComponent_div_0_div_4_Template (grant-deny-request-copy.component.html:4:11)
    at executeTemplate (core.mjs:9717:1)
    at refreshView (core.mjs:9580:1)
    at refreshEmbeddedViews (core.mjs:10731:1)
    at refreshView (core.mjs:9604:1)
    at refreshEmbeddedViews (core.mjs:10731:1)
    at refreshView (core.mjs:9604:1)
    at refreshComponent (core.mjs:10777:1)
    at refreshChildComponents (core.mjs:9376:1)
    at refreshView (core.mjs:9630:1)
```

The error is caused by this line

```html
<div *ngIf="!itemRequestRD.payload.decisionDate">
```

in the template file `src/app/request-copy/grant-deny-request-copy/grant-deny-request-copy.component.html`. I can confirm that `itemRequest.payload` is `null`.

The GET request to `https://dsbackend.tld/server/api/tools/itemrequests/<token>` returns the expected result, e.g.

```json
{
  "id" : 8,
  "decisionDate" : null,
  "expires" : null,
  "requestDate" : "2023-07-21T13:23:23.220+00:00",
  "token" : "2413ce949d784a79bc9f8824dbd42dbc",
  "acceptRequest" : false,
  "allfiles" : false,
  "type" : "itemrequest",
  "bitstreamId" : "b68ffc13-95bf-457c-8886-948e92beb187",
  "itemId" : "5ea06922-85d8-4b40-87a6-e1448adedc84",
  "requestEmail" : "doe@example.com",
  "requestName" : "Testuser",
  "requestMessage" : "Das ist eine Testnachricht.",
  "_links" : {
    "bitstream" : {
      "href" : "http://localhost:8080/server/api/tools/itemrequests/8/bitstream"
    },
    "item" : {
      "href" : "http://localhost:8080/server/api/tools/itemrequests/8/item"
    },
    "self" : {
      "href" : "http://localhost:8080/server/api/tools/itemrequests/8"
    }
  }
}
```

**Comment by saschaszott** [comment]
Sorry, this is a bug related to the Angular frontend. It was reopened in the dspace-angular project 👉 https://github.com/DSpace/dspace-angular/issues/2390
