### ISSUE TITLE
Docker Compose Create Administrator NullPointerException

### ISSUE THREAD

**Issue by ViaJables** [DSpace/DSpace#8998]
**Describe the bug**
In following the installation instructions for DSpace 7 using Docker, when issuing the data ingestion command

docker-compose -p d7 -f docker-compose-cli.yml run --rm dspace-cli create-administrator -e test@test.edu -f admin -l user -p admin -c en

It results in this following error

Exception: null
java.lang.NullPointerException
	at org.dspace.core.AbstractHibernateDAO.getHibernateSession(AbstractHibernateDAO.java:59)
	at org.dspace.core.AbstractHibernateDAO.createQuery(AbstractHibernateDAO.java:137)
	at org.dspace.eperson.dao.impl.GroupDAOImpl.findByName(GroupDAOImpl.java:104)
	at org.dspace.eperson.GroupServiceImpl.findByName(GroupServiceImpl.java:399)
	at org.dspace.administer.CreateAdministrator.createAdministrator(CreateAdministrator.java:257)
	at org.dspace.administer.CreateAdministrator.main(CreateAdministrator.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)

**Comment by tdonohue** [comment]
Cannot reproduce.  From the error described above, it sounds like your database may not have initialized properly and the "Administrator" group was not created (it should be created automatically when initializing the database).  I suspect some sort of error occurred during initialization or the database was inaccessible.

I'd recommend following the [troubleshooting guide](https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)) to look for underlying errors.  If you need more help, please use one of our [public support options](https://wiki.lyrasis.org/display/DSPACE/Support).
