### ISSUE TITLE
OAI endpoint throws HTTP 500 on multiple requests

### ISSUE THREAD

**Issue by ChrisBethgster** [DSpace/DSpace#9043]
**Describe the bug**
A harvester informed us, that the OAI endpoint throws a HTTP 500 on several times. The Harvester use the Method GetRecord in parallel Requests.
The problem is reproduced with JMeter.

**To Reproduce**
1. Disable the OAI file cache in configuration. We will allways do the XSLT transformation `oai.cache.enabled = false` in `modules/oai.cfg`
2. Do parallel GetRecord requests with valid identifiers (for example in metadataformat oai_dc)
3. Check the response of each request

Response header of an response with error
```
HTTP/1.1 500 
Server: nginx/1.23.4
Date: Tue, 29 Aug 2023 08:58:09 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Language: en
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
```

```
{"timestamp":"2023-08-29T08:58:09.541+00:00","status":500,"error":"Internal Server Error","message":"An exception has occurred","path":"/server/oai/request"}
```

![image](https://github.com/DSpace/DSpace/assets/54576195/818b4d42-fdc7-41d6-af2f-2e369e355073)

With the OAI file cache it was less or no probable, if the reults are often in the cache.

**Comment by ChrisBethgster** [comment]
https://github.com/DSpace/DSpace/blob/c7c30227ec4a4e5e2d4eb44ee78e04a1035a95b5/dspace-oai/src/main/java/org/dspace/xoai/services/impl/resources/DSpaceResourceResolver.java#L52

The documentation for the Transformer says "...  Care mustbe taken not to use this Transformer in multiple Threads running concurrently...". But we use the same transformer for all request with the same XSLT! Also for all mutliple requests with the same metadatformat. This isn't good.

With Saxon as transformer in the dspace log can be found
```
2023-08-29 10:43:30,731 ERROR unknown f26ea290-ecf8-4d67-b215-dc111f93c2fa org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.IllegalStateException: The Controller is being used recursively or concurrently. This is not permitted.
        at net.sf.saxon.Controller.checkReadiness(Controller.java:1854) ~[Saxon-HE-9.8.0-14.jar:?]
        at net.sf.saxon.Controller.transform(Controller.java:1884) ~[Saxon-HE-9.8.0-14.jar:?]
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596) ~[Saxon-HE-9.8.0-14.jar:?]
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73) ~[Saxon-HE-9.8.0-14.jar:?]
        at com.lyncode.xoai.util.XSLPipeline.apply(XSLPipeline.java:25) ~[xoai-3.3.0.jar:3.3.0]
        at com.lyncode.xoai.dataprovider.handlers.GetRecordHandler.handle(GetRecordHandler.java:64) ~[xoai-3.3.0.jar:3.3.0]
        at com.lyncode.xoai.dataprovider.OAIDataProvider.handle(OAIDataProvider.java:207) ~[xoai-3.3.0.jar:3.3.0]
        at com.lyncode.xoai.dataprovider.OAIDataProvider.handle(OAIDataProvider.java:229) ~[xoai-3.3.0.jar:3.3.0]
        at org.dspace.xoai.controller.DSpaceOAIDataProvider.contextAction(DSpaceOAIDataProvider.java:124) ~[dspace-oai-7.6.1-SNAPSHOT.jar:7.6.1-SNAPSHOT]
```

**Comment by ChrisBethgster** [comment]
The bug also exist in DSpace 6.x.

And the re-use of the transformer is a bad desgin approach. We must re-use the Template not the transformer, see https://www.saxonica.com/html/documentation12/using-xsl/compiling/caching.html

_The JAXP interface represents a compiled stylesheet as a Templates object. The object contains the entire stylesheet; all modules must be compiled as a single unit. ... The Templates object is thread-safe, so once created it can be used by many transformations running separately in parallel. To use the Templates object to run a transformation of a particular source document, a Transformer object is created. The Transformer is not thread-safe; its transform() method must not be called while a transformation is active. The Transformer can be serially reused, but with Saxon there is no benefit in doing so; better garbage collection generally occurs if a new Transformer is created for each transformation._

**Comment by ChrisBethgster** [comment]
Code changes necessary in xoai (see DSpace/xoai#86) and dspace-oai (see #9045).

I have temporarily change the XOAI version to 3.3.1-SNAPSHOT in my test environment. A maintainer should change this to valid version number...
