### ISSUE TITLE
When Solr cannot be found on startup, an odd NullPointerException may appear in logs *after* the important SolrServerException

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9217]
**Describe the bug**
If you attempt to startup the DSpace backend *without* Solr (or if the backend cannot connect to Solr on startup) you may see an obscure/odd error like the following in your logs:
```
2023-11-30 21:01:31,229 ERROR unknown unknown org.springframework.boot.SpringApplication @ Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationRestController': Unsatisfied dependency expressed through field 'converter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterService': Unsatisfied dependency expressed through field 'converters'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workflowItemConverter' defined in file [/dspace/webapps/server/WEB-INF/classes/org/dspace/app/rest/converter/WorkflowItemConverter.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dspace.app.rest.converter.WorkflowItemConverter]: Constructor threw exception; nested exception is java.lang.NullPointerException
...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterService': Unsatisfied dependency expressed through field 'converters'; 
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workflowItemConverter' defined in file [/dspace/webapps/server/WEB-INF/classes/org/dspace/app/rest/converter/WorkflowItemConverter.class]: Instantiation of bean failed;
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dspace.app.rest.converter.WorkflowItemConverter]: Constructor threw exception;
...
Caused by: java.lang.NullPointerException
  at org.dspace.app.rest.converter.AInprogressItemConverter.<init>(AInprogressItemConverter.java:63) ~[classes/:8.0-SNAPSHOT]
```

This obscure error is **misleading**, as the **root cause is that Solr is unavailable or the backend cannot communicate with Solr.**

**PRIOR TO** this exception, your logs will likely also display something like this:
```
2023-11-30 21:01:31,176 ERROR unknown unknown org.dspace.discovery.SolrSearchCore @ Error while initializing solr server http://dspacesolr:8983/solr/search
 org.apache.solr.client.solrj.SolrServerException: IOException occurred when talking to server at: http://dspacesolr:8983/solr/search
    at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:695)
```
This prior exception is the **root cause** and it can "snowball" into the later obscure BeanInstantiationException / NullPointerException shown above.

**To Reproduce**
1. Stop Solr
2. Reboot the DSpace backend (i.e. Tomcat) (as this error only occurs on startup if Solr is not available)
3. Watch the `dspace.log` file and you'll see the above exceptions. First the useful `SolrServerException`, but then the misleading `NullPointerException` related to beans.

**Expected behavior**
Ideally, we'd find a way to avoid or not display the misleading exception as it's not useful & appears to imply a configuration or Spring Bean error.  The important `SolrServerException` information is slightly hidden just above that misleading exception.

At this time, however, I'm unsure of the cause of this misleading exception. So, this ticket just documents that it *exists* so that others who encounter it know to look for the `SolrServerException` just above it.

**Comment by tdonohue** [comment]
Fixed by #9478 (8.x) and #9487 (7.x) as those PRs fixed the underlying issue with SubmissionConfigReader which caused these strange NullPointerExceptions to appear.  Now, you'll see an error specific to Solr if it is missing at startup.  For example:
```
Caused by: java.lang.RuntimeException: Failed to contact Solr at http://dspacesolr:8983/solr/search :  IOException occurred when talking to server at: http://dspacesolr:8983/solr/search
```
