### ISSUE TITLE
CLI dspace stats-log-converter is failing with undefined configFile

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9311]
**Describe the bug**
We are currently leaving legacy DSpace 5.X in favor of DS7 with completely new infrastructures. We had some statistical stored as logs that we want to recover and ingest it on the new system. But for the tests running so far, we can execute `stats-log-converter` command on DS5, but that same exact command doesn't work for DS7.

**To Reproduce**
1. Perform a 
```
/dspace/bin/dspace stats-log-converter -n -v -i dspace.2015-12-17.log-20151222 -o dspace-converted
```

An exception occurs:

```
Exception: null
java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at org.dspace.app.statistics.LogAnalyser.readConfig(LogAnalyser.java:986)
        at org.dspace.app.statistics.LogAnalyser.readConfig(LogAnalyser.java:956)
        at org.dspace.statistics.util.ClassicDSpaceLogConverter.main(ClassicDSpaceLogConverter.java:338)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:283)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:134)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:99)
```

**Expected behavior**
Digging a little bit, the error is related with configFile that is set as null.

```
    /**
     * the configuration file from which to configure the analyser
     */
    private static String configFile;
```

and this call:

    public static void readConfig() throws IOException {
        readConfig(configFile);
    }

when configFile is undefined.

The expected result was a csv file with the extracted content ready to be used with:
```
[dspace]/bin/dspace stats-log-importer
```

for ingesting log data into Solr.

**Related work**
[Link to any related tickets or PRs here](https://github.com/DSpace/DSpace/issues/2852)

**Comment by IgorBaptist4** [comment]
Hello, I work for Neki-IT and I would like to claim this issue.
