### ISSUE TITLE
CLI dspace stats-log-importer is failing with undefined configFile

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9312]
**Describe the bug**
We are currently leaving legacy DSpace 5.X in favor of DS7 with completely new infrastructures. We had some statistical stored as logs that we want to recover and ingest it on the new system. But for the tests running so far, we can execute stats-log-importer command on DS5, but that same exact command doesn't work for DS7.

**To Reproduce**

1. You can simply execute `stats-log-importer` command with an already converted file (csv format)
```
dspace/bin/dspace stats-log-importer -v -i dspace.2015-12-17.log-20151222`
```
An exception occurs:
```
Exception: null
java.lang.NullPointerException
        at org.dspace.statistics.util.StatisticsImporter.load(StatisticsImporter.java:290)
        at org.dspace.statistics.util.StatisticsImporter.main(StatisticsImporter.java:516)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:283)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:134)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:99)
```

**Expected behavior**

Digging a little bit, the error is related with geoipLookup that is set as null object.
[dspace-api/src/main/java/org/dspace/statistics/util/StatisticsImporter.java](https://github.com/DSpace/DSpace/blob/4bc95a31982831a04aad33f20b2a6e720aa7ff02/dspace-api/src/main/java/org/dspace/statistics/util/StatisticsImporter.java#L97)

```
private static DatabaseReader geoipLookup;
```

```
CityResponse cityResponse = geoipLookup.city(ipAddress);
```

that isn't defined when called. We were hopping to have that content ingested in Solr.

**Related work**
https://github.com/DSpace/DSpace/issues/9311

**Comment by IgorBaptist4** [comment]
Hello, I work for Neki-IT and I would like to claim this issue.
