### ISSUE TITLE
All e2e tests are resulting in error with "SuggestionTargetsEffects.refreshUserSuggestionsAction$"

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9355]
**Describe the bug**
After merging #8280 and https://github.com/DSpace/dspace-angular/pull/1638 , it appears a side effect has caused all our Angular e2e tests to hit backend errors of this sort:
```
ERROR Error: Effect "SuggestionTargetsEffects.refreshUserSuggestionsAction$" dispatched an invalid action: {}
    at reportInvalidActions (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:3979499)
    at /home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:3981691
    at /home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1883172
    at OperatorSubscriber2._this._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:184[2763](https://github.com/DSpace/dspace-angular/actions/runs/7999721964/job/21848005988?pr=2275#step:14:2764))
    at OperatorSubscriber2.Subscriber2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793325)
    at OperatorSubscriber2.Subscriber2._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793888)
    at OperatorSubscriber2.Subscriber2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793325)
    at /home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1887395
    at OperatorSubscriber2._this._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1842763)
    at OperatorSubscriber2.Subscriber2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793325)
...
ERROR TypeError: Actions must have a type property
    at ActionsSubject.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:4005625)
    at Store2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:4015611)
    at ConsumerObserver2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1794591)
    at SafeSubscriber2.Subscriber2._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793888)
    at SafeSubscriber2.Subscriber2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793325)
    at /home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1887395
    at OperatorSubscriber2._this._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1842763)
    at OperatorSubscriber2.Subscriber2.next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1793325)
    at /home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1887395
    at OperatorSubscriber2._this._next (/home/runner/work/dspace-angular/dspace-angular/dist/server/main.js:7:1842763)
```

These errors appear "harmless" but they fill up the logs of the e2e tests.  They need to be fixed as they make other e2e errors difficult to locate.

**To Reproduce**
1. Either run `yarn e2e` locally
2. Or see results of e2e tests for any recent `dspace-angular` PR or on `main`.  For example https://github.com/DSpace/dspace-angular/actions/runs/8001316721/job/21852298415#step:14:79

**Expected behavior**
This error should not occur.

**Comment by tdonohue** [comment]
@frabacche or @abollini : I need 4Science's attention on this as I believe it's related to #8280 .  I'm seeing consistent errors from the backend regarding this "invalid action" especially when running the UI's e2e tests.  This appears, to me, to be a backend error.

Assigning this to both of you, feel free to delegate.

**Comment by frabacche** [comment]
> @frabacche or @abollini : I need 4Science's attention on this as I believe it's related to #8280 or [DSpace/dspace-angular#1638](https://github.com/DSpace/dspace-angular/pull/1638) . I'm seeing consistent errors from the ~backend~ frontend regarding this "invalid action" especially when running the UI's e2e tests. ~This appears, to me, to be a backend error, but I could be wrong.~ On second analysis, this appears to be a **frontend** error. But, I'll leave it in your capable hands either way
> 
> Assigning this to both of you, feel free to delegate.

hi @tdonohue  -  @FrancescoMolinaro is taking care of this one.

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue  I have addressed the issue here:

https://github.com/DSpace/dspace-angular/pull/2830

We handle now the error and it does not appear anymore during the e2e tests.
May kindly ask you to review the pull request?
