### ISSUE TITLE
Assertion error during submission save/submit when choosing author name from ORCID list

### ISSUE THREAD

**Issue by parphis** [DSpace/DSpace#9424]
**Describe the bug**
DSpace 7.6.1 backend and UI. It is not clear whether the UI or the backend causes the issue but I bet on backend.

Submitting a new item from the UI drops the error 'There was an issue when saving the item, please try again later.' when I choose an author name from the ORCID list of users. There is no any error on the developer console.

**To Reproduce**
1. Create a simple submission form for a given collection with only two mandatory fields: `dc.title` and `dc.contributor.author` and with license and file upload steps.
2. Add/change the configuration parameters as per the description at https://wiki.lyrasis.org/display/DSDOC7x/ORCID+Authority.
3. Login to the UI, navigate to the collection and click on New -> Item.
4. Enter any name for the author field.
5. Press the Search button and choose one name from the list. The grey circle changes to green.
6.
    1. Now when I press the Save button (or check the licence confirmation or upload a new file) the UI displays the described error message. The DSpace log contains the following line:  
`2024-03-18 22:57:54,442 ERROR 1434b685-1a8f-4e92-8339-7b8cbc3ae3c3 3740a274-be08-4b74-b8b8-2ded04475b3a org.dspace.app.rest.submit.SubmissionService @ [Assertion failed] - this collection must not be empty: it must contain at least 1 element java.lang.IllegalArgumentException: [Assertion failed] - this collection must not be empty: it must contain at least 1 element`
The table `metadatavalue` does not lists the newly entered and chosen name. I think this causes the error above. Some records are generated but not the `dc.author.contributor` (sligthly modified source code for debug purposes this is why the explamation marks in the log):
`2024-03-18 22:57:00,677 INFO  1434b685-1a8f-4e92-8339-7b8cbc3ae3c3 dd5dccdc-06e1-4b6d-a2f3-12952f71b1bb org.dspace.content.MetadataValueServiceImpl @ user@user::add_metadatavalue:metadata_value_id=1884476!!!metadata_field=type null!!!metadata_value=null`
    2. If I start a new submission or change / edit the author name w i t h o u t choosing an ORCID user from the list (the circle is greyed now close to the family name) and I press the Save button the UI will not display the show stopper error and the `metadatavalue` table will have the record with the given name (empty authority field with confidence val of -1). And now when I press again the Search button and choose the ORCID user from the list and press again the Save button (or enter the other mandatory fields and Submit the item) the submission will be done without error. (If I press the Save button the record for the author in the table `metadatavalue` will change the value of the authority field to 'will be generated:orcid...' and the confidence will be 600).

**Expected behavior**
Choosing the author from an ORCID list should work like entering a simply name.

**Related work**
I tried to find a way to test this on the DSpace Demo site but I did not find a submission where the author can be selected from an ORCID user list.

Finally, here is a little bit of longer DSpace log regarding the Assertion error:
```bash
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ item name:null
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ schema:dc, element:title, qualifier:
2024-03-18 12:14:57,022 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ no values found
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ ###getMetadataByMetadataString###
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ mdString:dc.contributor.author
2024-03-18 12:14:57,022 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ item name:null
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ schema:dc, element:contributor, qualifier:author
2024-03-18 12:14:57,022 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,022 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ no values found
2024-03-18 12:14:57,035 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.WorkspaceItemServiceImpl @ user@user::find_workspace_item:workspace_item_id=54714
2024-03-18 12:14:57,035 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.app.util.SubmissionConfigReader @ Loading submission process config named 'bmeomikk-diszi'
2024-03-18 12:14:57,035 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.app.util.SubmissionConfigReader @ Found submission process config 'bmeomikk-diszi' in cache.
2024-03-18 12:14:57,039 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,040 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.MetadataValueServiceImpl @ user@user::add_metadatavalue:metadata_value_id=1884373
2024-03-18 12:14:57,040 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.app.util.SubmissionConfigReader @ Loading submission process config named 'bmeomikk-diszi'
2024-03-18 12:14:57,040 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.app.util.SubmissionConfigReader @ Found submission process config 'bmeomikk-diszi' in cache.
2024-03-18 12:14:57,045 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ ###getMetadataByMetadataString###
2024-03-18 12:14:57,045 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ mdString:dc.contributor.author
2024-03-18 12:14:57,045 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 with invalid cache
2024-03-18 12:14:57,045 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 without enableVirtualMetadata
2024-03-18 12:14:57,045 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,045 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ item name:teszt cím
2024-03-18 12:14:57,045 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ schema:dc, element:contributor, qualifier:author
2024-03-18 12:14:57,045 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,045 INFO  e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.DSpaceObjectServiceImpl @ no values found
2024-03-18 12:14:57,045 DEBUG e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.content.Item @ Called getMetadata for b55aea73-f0ca-4249-b15d-c79e26806802 based on cache
2024-03-18 12:14:57,045 ERROR e771a04c-7c71-4f80-8792-e63fd9a9eea5 ec195b3e-6499-419a-9e32-90f4630e9f1d org.dspace.app.rest.submit.SubmissionService @ [Assertion failed] - this collection must not be empty: it must contain at least 1 element
java.lang.IllegalArgumentException: [Assertion failed] - this collection must not be empty: it must contain at least 1 element
    at org.springframework.util.Assert.notEmpty(Assert.java:470) ~[spring-core-5.3.27.jar:5.3.27]
    at org.springframework.util.Assert.notEmpty(Assert.java:500) ~[spring-core-5.3.27.jar:5.3.27]
```

**Comment by saschaszott** [comment]
We (at openhsu.de) encountered the same error message (`[Assertion failed] - this collection must not be empty: it must contain at least 1 element`).

It is triggered by this line in the backend code

https://github.com/DSpace/DSpace/blob/867e056f4aa6d933c97ceae8e543d6ed362086f9/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/ItemMetadataValueReplacePatchOperation.java#L59

We do **not** use ORCID, and I currently have no clue what causes this issue (it results in an HTTP 500 error). Could it be a form state mismatch between frontend and backend?

**Comment by saschaszott** [comment]
This issue might be related to a similar one reported in the DSpace Angular repository: https://github.com/DSpace/dspace-angular/issues/3050

It was fixed in DSpace 7.6.2

**Comment by saschaszott** [comment]
@parphis , are you able to reproduce the bug in a newer DSpace version (7.6.2 or higher)?

**Comment by parphis** [comment]
@saschaszott I migrated our servers to 8.1 in June this year.
Using this version I _was not able_ to reproduce the issue as described above anymore so it has been solved.

**Comment by saschaszott** [comment]
@parphis , thanks!
