### ISSUE TITLE
OpenAIRE import from external source doesn't work

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9501]
**Describe the bug**
It is not possible to import content from OpenAIRE using the "Import from external sources" options on the MyDSpace page.  Additionally, the descriptions are missing for these import sources (see screenshot):

![openaire-broken](https://github.com/DSpace/DSpace/assets/483997/c5774f26-a5d2-4187-b145-8845f1738fce)

**To Reproduce**
1. Go to MyDSpace
2. Click the import button & select "Publication"
3. Select one of the two (unlabeled) OpenAIRE sources.  Attempt to run any search.  All searches will error out.  Behind the scenes in the DSpace log, this error occurs:
```
2024-04-24 21:31:01,268 ERROR ec49885b-3617-4441-a022-20dcf8505f51 29158a6e-5111-4a00-ae35-2cded0051dfc org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
 java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.dspace.importer.external.openaire.service.OpenAireImportMetadataSourceServiceImpl.retry(java.util.concurrent.Callable)" is null
   at org.dspace.importer.external.openaire.service.OpenAireImportMetadataSourceServiceImpl.getRecordsCount(OpenAireImportMetadataSourceServiceImpl.java:94) ~[dspace-api-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
   at org.dspace.external.provider.impl.LiveImportDataProvider.getNumberOfResults(LiveImportDataProvider.java:113) ~[dspace-api-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
   at org.dspace.external.service.impl.ExternalDataServiceImpl.getNumberOfResults(ExternalDataServiceImpl.java:92) ~[dspace-api-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
   at org.dspace.app.rest.repository.ExternalSourceRestRepository.getExternalSourceEntries(ExternalSourceRestRepository.java:78) ~[dspace-server-webapp-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
```

**Expected behavior**
Obviously, these searches should not throw errors.  Additionally, we need to add translation keys for these two OpenAIRE sources to the `en.json5` file in dspace-angular.  They likely should say something like this:
```
"submission.import-external.source.openaire": "OpenAIRE Search by Author",

"submission.import-external.source.openaireTitle": "OpenAIRE Search by Title",
```

**Related work**
Unclear where this error began.

**Comment by tdonohue** [comment]
Created a small PR to fix the missing i18n keys issue: https://github.com/DSpace/dspace-angular/pull/2979

This PR however needs a volunteer to investigate why these imports are no longer working

**Comment by tdonohue** [comment]
@abollini : Just a reminder that this ticket is also assigned to 4Science.  If possible, it'd be good to see a PR in the next week as we are hoping to get this into 8.0.

**Comment by tdonohue** [comment]
@abollini : I've figured out how to solve this and created a PR in #9631 .  This small PR fixes the bug and includes some minor code cleanup (of issues found during debugging).

Therefore, I'll claim this ticket from you & assign you as the PR reviewer for #9631.  However, feel free to delegate as needed.
