### ISSUE TITLE
DSpace API problems in editing items and long load times 

### ISSUE THREAD

**Issue by aseyedia** [DSpace/DSpace#9879]
## Describe the bug

[Originally posted in DSpace Slack.](https://dspace-org.slack.com/archives/C3V628QNN/p1728398019387289)

Hello all. I'm building up and managing two separate instances of DSpace. We're getting close to launch and it seems like there is this new issue that has slowly emerged in both of these two separate instance, in both the dev and production side of things.
When a user is logged in, the site becomes extremely sluggish and editing items becomes a pain; users (so far only admins) will get stuck in an "infinite loading loop" and often we will have to refresh multiple times to get it to work, especially and particularly around editing items.

In the console, for both instances A and B, there is a not-identical-but-very-similar inscrutable wall of error text that appears that nonetheless seems to suggest that this is some sort of API issue.

On both of the development instances (the production instances' error output is not helpful because they're all pointing to generated JavaScript scripts), the error looks like this:

```
ERROR Error: {"actuator":{"href":"https://pedsdspace01.research.chop.edu/server/actuator"},"authn":{"href":"https://pedsdspace01.research.chop.edu/server/api/authn"},"authorizations":{"href":"https://pedsdspace01.research.chop.edu/server/api/authz/authorizations"},"bitstreamformats":{"href":"https://pedsdspace01.research.chop.edu/server/api/core/bitstreamformats"},"bitstreams":{"href":"https://pedsdspace01.research.chop.edu/server/api/core/bitstreams"},"browses":{"href":"https://pedsdspace01.research.chop.edu/server/api/discover/browses"},"bulkaccessconditionoptions":
[...dozens of endpoints...]
{"href":"https://pedsdspace01.research.chop.edu/server/api/config/workflowdefinitions"},"workflowitems":{"href":"https://pedsdspace01.research.chop.edu/server/api/workflow/workflowitems"},"workflowsteps":{"href":"https://pedsdspace01.research.chop.edu/server/api/config/workflowsteps"},"workspaceitems":{"href":"https://pedsdspace01.research.chop.edu/server/api/submission/workspaceitems"}} doesn't contain the link profiles
    at hal-endpoint.service.ts:93:17
    at map.js:7:37
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at map.js:7:24
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at take.js:12:32
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
```

However, yarn test:rest shows that the API is accessible and working:

```
[dspace@pedsdspace01 dspace-angular-dspace-8.0]$ yarn test:rest
yarn run v1.22.22
$ ts-node --project ./tsconfig.ts-node.json scripts/test-rest.ts
[...]
Checking JSON returned for validity...
        "dspaceVersion" = DSpace 8.0
        "dspaceUI" = https://pedsdspace01.research.chop.edu/
        "dspaceServer" = https://pedsdspace01.research.chop.edu/server
        "dspaceServer" property matches UI's "rest" config? true
        Does "/api" endpoint have HAL links ("_links" section)? true
Done in 1.70s.
```

I later found out that it had nothing to do with SSL and the main issue was that I hadn't set up [Profiles](https://wiki.lyrasis.org/display/DSDOC8x/Researcher+Profiles) (`[...] doesn't contain the link **profiles**`). I simply enabled it and I no longer have this issue.

## To Reproduce
1. Try to use DSpace (especially editing items) without enabling [Profiles](https://wiki.lyrasis.org/display/DSDOC8x/Researcher+Profiles).

## Expected behavior
No long load times, no API issues in the console.

**Comment by aseyedia** [comment]
This wasn't the source of my problem, I just realized.

**Comment by aseyedia** [comment]
Retiring this issue in favor of https://github.com/DSpace/DSpace/issues/9879
