### ISSUE TITLE
When abstract includes :: in the input, import throws an error.

### ISSUE THREAD

**Issue by misilot** [DSpace/DSpace#9896]
## Describe the bug
A clear and concise description of what the bug is.  Include the version(s) of DSpace where you've seen this problem. Link to examples if they are public.

## To Reproduce
1. Create record with `To test our hypothesis, we created mutant strains R20291::licB and R20291:: cd2781 using ClosTron mutagenesis system.` in the abstract
2. Then try and use the metadata import function to update the record.

Get error like
```
2024-10-14 21:12:12.543 INFO metadata-import - 37 @ The script has started
2024-10-14 21:13:49.735 ERROR metadata-import - 37 @ null
2024-10-14 21:13:49.738 ERROR metadata-import - 37 @ java.lang.NumberFormatException: For input string: " cd2781 using ClosTron mutagenesis system. The resulting mutants showed a differential level of virulence factors, which were also corroborated by different molecular techniques. We also identified the CD2781 as a negative transcriptional regulator of cellobiose operon, characterized its target binding attributes, determined its role in virulence, and named it as CelR. Our hamster infection model study demonstrates that cellobiose PTS operon is essential for colonization, pathogenesis, and recurrent infection of C. difficile in hamsters.  These works, in conclusion, demonstrate that both glycogen and cellobiose metabolism plays a significant role in C. difficile virulence."
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at org.dspace.app.bulkedit.MetadataImport.compareAndUpdate(MetadataImport.java:748)
	at org.dspace.app.bulkedit.MetadataImport.runImport(MetadataImport.java:415)
	at org.dspace.app.bulkedit.MetadataImport.internalRun(MetadataImport.java:217)
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:150)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Expected behavior
Record should update

## Related work
From Slack: https://dspace-org.slack.com/archives/C3V628QNN/p1729021504851519

>Tim Donohue
>  Yesterday at 4:06 PM
>Oh, it looks like that parseInt() is on this line: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java#L748
>Which means it wrongly thinks the abstract is an Authority Control field.  The abstract must include the csv.getAuthoritySeparator() (which is a :: I believe), since it triggers the else under here: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java#L742

**Comment by tdonohue** [comment]
@ybnd : I've just realized this sounds *very similar* to #9749.  Do you happen to know if this is the same issue?  If so, we should consider backporting your fix in #9753 to 8.x and 7.x 

This same issue was also recently mentioned on dspace-tech: https://groups.google.com/g/dspace-tech/c/IyhGBF2yqTU

**Comment by ybnd** [comment]
@tdonohue @misilot This is a related issue for sure, but looks like just backporting won't be enough. On DSpace 9 the import comes through, but everything after the first double colon gets discarded.

Example:
- https://sandbox.dspace.org/processes/10
- https://sandbox.dspace.org/processes/12

We could tackle that DSpace 9 bug first and backport both fixes to 7 & 8.

**Comment by tdonohue** [comment]
@ybnd : If you are willing to claim this, I'd very much appreciate it.  It obviously won't make it into 9.0, but maybe we can get a fix ready for 9.1 and upcoming bug fix releases for 7.6.x and 8.x

Assigning to you.

**Comment by ybnd** [comment]
@tdonohue since this was marked as maintenance, would you agree to backport https://github.com/DSpace/DSpace/pull/9753 to 7.x and 8.x as well?

**Comment by tdonohue** [comment]
@ybnd : I'm not against someone backporting #9753 to 8.x and 7.x.   It looks like that was simply merged quickly before anyone added the `port to __` labels, so it was not backported automatically.  In the future, you are welcome to add those labels yourself to your PRs if you feel it *should be backported*.
